### ISSUE TITLE
Playback of Voice message stops whenever phone is rotated and changes orientation

### ISSUE THREAD

**Issue by lullis** [vector-im/element-android#4198] opened 2021-10-10 10:14 UTC
### Steps to reproduce

 1. Start playing a voice message that you received.
 1. Rotate the phone to change orientation portrait <-> landscape.

#### What did you expect?

Voice message to be kept playing

#### What happened instead?

Voice message stops and reset (i.e, playing it again starts it from beginning)

### Your phone model

Fairphone 3

### Operating system version

/e/ OS

### Application version and app store

F-Droid

### Have you submitted a rageshake?

No

**Comment by ZianeA** [comment] 2021-10-17 18:57
There are many approaches to handling this. WhatsApp, for example, plays voice messages in a foreground service. Youtube, on the other hand, seems to handle rotation by pausing the playback after a delay. If the `onResume` callback method is called within that delay, the video is never paused.

However, after I've investigated the bug, I found other related issues:
#### DI issue:
`VoiceMessagePlaybackTracker` is annotated with `@ScreenScope`, so it's scoped to the screen (Activity). Whenever the system recreates the Activity due to configuration changes (including but not limited to rotation), Dagger injects it with a new instance of `VoiceMessagePlaybackTracker`. The problem is that the `RoomDetailViewModel` has a transitive dependency on `VoiceMessagePlaybackTracker`. Since the ViewModel survives configuration changes, which means it has a longer lifespan, its instance of `VoiceMessagePlaybackTracker` will be different from that of the Activity after configuration changes.

A possible solution to this problem is to add the playback time to the screen state instead of a separate object.   

#### Other issues:
* There could be concurrency issues with the `VoiceMessageHelper` class. The `RoomDetailViewModel` invokes the `startOrPausePlayback` function from a background thread where it modifies the shared mutable variable `mediaPlayer`.  

* Per the [Android docs](https://developer.android.com/guide/topics/media/mediaplayer#releaseplayer), it's recommended to release the `MediaPlayer` when not used.

**Comment by ouchadam** [comment] 2021-11-24 17:31
closing as a duplicate of #4067, will be fixed with https://github.com/vector-im/element-android/pull/4556

**Closed by ouchadam** 2021-11-24 17:31 UTC
Labels: T-Defect
