### ISSUE TITLE
Presence indicator rendering over avatar 

### ISSUE THREAD

**Issue by Dan904** [vector-im/element-android#5585] opened 2022-03-18 22:53 UTC
### Steps to reproduce

1. Open DM on element android
2. Look at the top tool bar

#### What did you expect?

The presence indicator used to be in the bottom right corner of the avatar circle. 

#### What happened instead?

The encryption shield is now in the bottom right corner and the presence indicator is in the middle of the avatar circle. 

![Screenshot_20220318-185103](https://user-images.githubusercontent.com/2293959/159094472-bcfd48c9-f3df-4281-a517-cb0730c29664.png)

![Screenshot_20220318-185228](https://user-images.githubusercontent.com/2293959/159094496-1efee009-4fdc-44f9-b261-934bd71905c5.png)

### Your phone model

Google pixel 5

### Operating system version

Android 12

### Application version and app store

Element version 1.4.4 [40104042] (G-b6763)

### Will you send logs?

No

**Comment by R4DIC4L** [comment] 2022-03-19 15:24
This is happening on more android devices, I am having the same issue on a Samsung S10+ with android 12 and a friend is having the same issue on a OnePlus 6T with android 11.

Maybe the presence indicator can be placed in the bottom-left corner instead, to have both presence (left) and shield (right) indicators under the circular user image?

**Comment by notramo** [comment] 2022-03-20 11:58
It's **very** common. There's another issue for it: #5489

**Comment by ouchadam** [comment] 2022-03-21 15:52
thanks for raising! going to close as a duplicate of #5489 

hopefully we'll get this in before next release :crossed_fingers:

**Closed by ouchadam** 2022-03-21 15:52 UTC
Labels: T-Defect
