### ISSUE TITLE
Headphone is ignored when plugged during voip call

### ISSUE THREAD

**Issue by symphorien** [vector-im/element-android#2242] opened 2020-10-10 19:10 UTC
**Describe the bug**
If headphones are connected *during* a voip call, elements show the output selector as if headset is was chosen but it is still ouputing sound by the loudspeaker.

**To Reproduce**
1. Unplug the headset
2. Accept a voip call
3. The loudspeaker is used
4. Plug the headset

**Expected behavior**
The headset is used

**Actual behavior**
The loudspeaker is still used.
The sound output select displays (wrongly) that it is using the headset.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 7
 - OS: Lineage OS 17.1 / Android 10
**Additional context**
 - App version and store 1.0.8 F-droid
 - Homeserver: xlumurb.eu

Headphones do work if they were already plugged before accepting the call.

**Comment by jpggithub** [comment] 2020-11-04 20:56
Same behavior with Element 1.0.9 (F-droid), olm 3.1.2 with Lineageos 17.1 (Android 10 without gapps)

**Comment by notramo** [comment] 2020-12-02 11:35
Is it ignored when plugging in, but can you switch to it manually?
Maybe it's ignored because it isn't even recognised by the app (#2195).

**Comment by Victor239** [comment] 2020-12-03 10:29
I haven't been able to manually switch to it.

**Comment by symphorien** [comment] 2020-12-24 12:44
When I plug the headset, the app displays it is using the headset, but in reality it uses the loudspeaker. It offers me to switch to the loudspeaker, but pressing the button has no effect. 

I tried with 1.0.11 [40100110] (F-dffdcfe1) from f-droid

**Comment by kittykat** [comment] 2021-11-17 16:44
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat if you can reproduce it in v1.3.8 (coming out next week) and I will re-open the issue

**Closed by kittykat** 2021-11-17 16:44 UTC
Labels: A-VoIP
