### ISSUE TITLE
Missing letters in rainbow text

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-android#4939] opened 2022-01-13 13:39 UTC
### Steps to reproduce

1. Send message using rainbowme from Element Web `/rainbowme wonders why file pills look so vastly different between Web & Android`
2. Open message in Element Android

#### What did you expect?
All letters to be rendered

![image](https://user-images.githubusercontent.com/2403652/149340990-3cd57126-c57a-42c4-8bd8-a5347581887c.png)

#### What happened instead?
The `i` in `file` is just missing

![image](https://user-images.githubusercontent.com/2403652/149340527-ae4aa375-87d6-474b-b16b-5d789e5f06b5.png)

### Your phone model

Samsung S20U

### Operating system version

Android 11

### Will you send logs?

No

**Comment by bmarty** [comment] 2022-01-13 16:23
Tested with this event and the bad color and it worked...

```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.emote",
    "format": "org.matrix.custom.html",
    "body": "Alors avec bad en couleur ff9000",
    "formatted_body": "Alors: <font color=\"#ff9000\">bad</font>"
  }
}
```

<img width="461" alt="image" src="https://user-images.githubusercontent.com/3940906/149368624-163a22f4-cf0d-4188-b975-2bfd344b68e8.png">

**Comment by t3chguy** [comment] 2022-01-13 16:33
What about `i` in that colour regardless of the rest of the event?

**Comment by G2G2G2G** [comment] 2022-01-17 05:08
Just FYI this doesn't do that on F-DROID version  (S8 Android version 9)

tried to do some different sized names (yea screenshot doesn't show capital A on Android but I tried all of those variations too, as well as full alphabet)
![1](https://user-images.githubusercontent.com/50514477/149710666-44ab6dd5-4ae4-4ade-8fdd-c529eb879424.jpg)

**Comment by ahmed-radhouane** [comment] 2022-02-24 08:41
I reviewed the code and I have tried extreme cases, (more spaces, symbols, repetitive letters ... ) and I do not get to the issue. 
Do you still have the problem. 
If so any details about the scenario ? 
cc @t3chguy

**Comment by bmarty** [comment] 2022-02-24 08:57
@ahmed-radhouane sending the message `/rainbowme wonders why file pills look so vastly different between Web & Android` in a room to see the problem of missing `i` in `file` (as per the issue description).

Just tested again on latest 1.4.2, the issue is still there.

Maybe not visible on all device? I am running  on an Android 10 device FTR.

**Comment by ahmed-radhouane** [comment] 2022-03-04 07:49
Hello, some remarks about this issue : 
1 - It's was tested on Samsung Note8 Android 12 = > No problem. 
And on samsung S21 Ultra, Android 12 : I had the issue. 
So, I guess it depends on the resolution and screen scale. 

2 - it's not only on /rainbowme command also /rainbow had the problem. 

3 - Not only with the word 'file' that we get the problem. any world with lower case 'f' followed by lower case 'i' create the issue. And the doesn't really disappear but it get behind the next letter. 
Example : in word 'file' the i get behind the 'l' but it is not noticed but in the word 'fire' we can see the dot of the letter 'i' which is behind the letter 'r'

**Comment by bmarty** [comment] 2022-03-08 08:58
Thanks for your investigation @ahmed-radhouane 
According to your feedback, I am not sure we can do anything to fix this issue. Let's close it :/

**Closed by bmarty** 2022-03-08 08:58 UTC
Labels: T-Defect, A-Timeline, S-Minor, O-Uncommon, Z-WTF, Z-Ready
