### ISSUE TITLE
Wrong numbering interpretation on Android mobile clients?

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-android#2189] opened 2020-09-30 10:55 UTC
During a conversation with mixed Element clients (Desktop- and Android-Element) we noticed that sometimes sentences starting numbered are listed in a wrong way, for exmample: If one asks "10. October is okay for you?" the post is listed as "1. October is okay for you?" on Android-Element. Compare the red bordered posts in the screenshots:

![numbering-problem_20200929_android](https://user-images.githubusercontent.com/44623983/94679067-c772ef80-031f-11eb-9d17-bd84fd5af508.jpg)
![numbering-problem_20200929_linux](https://user-images.githubusercontent.com/44623983/94679074-ca6de000-031f-11eb-9628-b3405454b58c.png)

Unfortunately I was not able to reproduce the problem but i happens two times from two different Android-Element clients (one installed from PlayStore, one from F-Droid). I know this is not a very "clear" bugreport but this is a bug which can cause big trouble in professional collaboration.

**Comment by tormodvolden** [comment] 2021-01-22 16:24
This must be a duplicate of #289. Confirmed on Element-Android 1.0.14.

If I enter (in Element-web):
```
4. Four
3. Three
2. Two
1. One
```

I will see in Element-web:
```
4. Four
5. Three
6. Two
7. One
```

And on Element-Android:
```
1. Four
2. Three
3. Two
4. One
```

**Comment by ouchadam** [comment] 2022-05-23 08:33
Going to centralise the issue to #4777

**Closed by ouchadam** 2022-05-23 08:33 UTC
Labels: A-Markdown
