### ISSUE TITLE
Crash about UrlPreview

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2641] opened 2021-01-08 16:59 UTC
Crash occurs after leaving room (not tested by myself)

```
Thread: main, Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:24)
at im.vector.app.VectorApplication_MembersInjector.with(VectorApplication_MembersInjector.java:23)
at im.vector.app.features.media.ImageContentRenderer.render(ImageContentRenderer.kt:3)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlView.renderData(PreviewUrlView.kt:7)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlView.render(PreviewUrlView.kt:8)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlView.render$default(PreviewUrlView.kt:1)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem$PreviewUrlViewUpdater.onStateUpdated(MessageTextItem.kt:2)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlRetriever.updateState(PreviewUrlRetriever.kt:5)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlRetriever.access$updateState(PreviewUrlRetriever.kt:1)
at im.vector.app.features.home.room.detail.timeline.url.PreviewUrlRetriever$getPreviewUrl$$inlined$let$lambda$1.invokeSuspend(PreviewUrlRetriever.kt:15)
```

https://github.com/matrix-org/element-android-rageshakes/issues/18005

**Comment by onurays** [comment] 2021-01-21 12:51
Duplicate of #2640

**Closed by onurays** 2021-01-21 12:51 UTC
Labels: crash
