### ISSUE TITLE
Badly formatted mentions in body

### ISSUE THREAD

**Issue by f0x52** [vector-im/element-android#1506] opened 2020-06-19 13:29 UTC
RiotX transforms mentions to `\"Displayname\" (https://matrix.to/#/@mxid)` in the `body` key, which makes for some very messy IRC bridging, as opposed to Riot Web's `body` key that just uses `Displayname`

**Comment by f0x52** [comment] 2020-06-19 15:18
This is an issue with the markdown conversion, disabling that in settings puts plain `Displayname` in the `body`

**Comment by bmarty** [comment] 2020-06-22 07:39
Yes, this is due to https://github.com/vector-im/riotX-android/commit/b29c2b2de4a40ead378ee597164d824d4ae8b3a1

The body cannot contains link, so they are added between parenthesis. Haven't though of the side effect for mentions, but I do not really understand the problem about IRC bridging?

**Comment by auscompgeek** [comment] 2020-06-22 07:42
> I do not really understand the problem about IRC bridging?

The IRC bridge uses the `body` for messages sent from Matrix to IRC. So this is resulting in messages that would look like `"auscompgeek" (https://matrix.to/#/@freenode_auscompgeek:matrix.org): blah`.

**Comment by turt2live** [comment] 2020-06-23 17:14
fwiw the spec on this is https://matrix.org/docs/spec/client_server/r0.6.1#user-room-and-group-mentions

**Comment by auscompgeek** [comment] 2020-07-01 04:34
It looks like this also affects room pills.

**Comment by Cadair** [comment] 2020-07-01 11:12
It's not just the IRC bridge it's also various bots which parse the plain text, please follow the spec and Riot web :smile:

**Comment by progserega** [comment] 2020-07-21 03:18
This is bad for bots. Today I try fix bug, when bot on answer my (when I call it from element-android). And I got this:

event source from Riot web :
```
"body": "bot_name: help",
"formatted_body": "<a href=\"https://matrix.to/#/@bot_name:server.com\">bot_name</a>: help"
```

event source from Element-android:
```
"body": "\"bot_name\" (https://matrix.to/#/@bot_name:server.com): help",
"formatted_body": "<a href=\"https://matrix.to/#/@bot_name:server.com\">bot_name</a>: help"
```
Situation, when bot must add ugly hacks to workaround clients specific - is bad!

**Comment by erdnaxeli** [comment] 2020-07-29 15:13
I should mention it does not only affect bridges or bot, it only affects clients wich are not using the formatted body like the weechat script.

**Comment by bmarty** [comment] 2020-09-10 13:39
It is not the case anymore in Element 1.0.6

**Comment by ilmari** [comment] 2020-09-10 14:16
@bmarty I'm still seeing this in 1.0.6:

```json
{
  "type": "m.room.message",
  "sender": "@ilmari:ilmari.org",
  "content": {
    "msgtype": "m.text",
    "body": "[ilmari](https://matrix.to/#/@_ircnet_ilmari:irc.snt.utwente.nl): yo",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@_ircnet_ilmari:irc.snt.utwente.nl\">ilmari</a>: yo"
  },
  "origin_server_ts": 1599747099796,
  "unsigned": {
    "age": 96
  },
  "event_id": "$8n1q-Imu7vdtSN6NWhZTERnqQa2PlqUUV66PH_5U2VQ",
  "room_id": "!fcJxhrfpmnNjJqlvnb:irc.snt.utwente.nl"
}
```
![Screenshot from 2020-09-10 15-14-10](https://user-images.githubusercontent.com/72175/92743484-7c953600-f378-11ea-8955-9467f1b48e97.png)
![Screenshot_20200910-151250](https://user-images.githubusercontent.com/72175/92743488-7d2dcc80-f378-11ea-8ff1-8c5969064fe7.png)

**Comment by turt2live** [comment] 2020-09-10 16:51
yea, it's still incorrect.

**Comment by bmarty** [comment] 2020-09-14 07:52
Just tested it on 1.0.6 production and I confirm the bug is there. I do not understand, the code to fix that is in 1.0.6...

Not reproduced on 1.0.7-dev though.

Please confirm that it's well fixed on 1.0.7...

**Comment by turt2live** [comment] 2020-09-14 13:47
seems fixed on whatever the current develop build is

**Comment by emorrp1** [comment] 2020-09-24 12:05
@bmarty F-Droid today updated to 1.0.7, but I'm sorry to say with `/markdown on` (and a full stop and start) I still have the same  mention formatting issue as @ilmari updated above. Please re-open this issue.

**Comment by auscompgeek** [comment] 2020-09-24 15:31
With 1.0.7 from Play Store, I no longer have the pills plaintext as mentioned in this issue, but I get a _different_ plaintext that is still wrong (specifically what looks like Markdown).

**Comment by bmarty** [comment] 2020-09-25 07:14
> @bmarty F-Droid today updated to 1.0.7, but I'm sorry to say with `/markdown on` (and a full stop and start) I still have the same mention formatting issue as @ilmari updated above. Please re-open this issue.

I will only be fixed on new sent messages. The bug will not be fixed for already sent messages with a previous version of the app

**Comment by emorrp1** [comment] 2020-09-25 23:21
@bmarty yes, these are new messages written after upgrading and it sounds like this is reproducible from Play Store too, so there's something included in @turt2live's "current develop build" that is missing from the final tagged release.

`"body": "[pixel](https://matrix.to/#/@pixel8383:matrix.org): mention test"` -- [source](https://matrix.to/#/!jrrfdpcKPllUsyVuBf:matrix.org/$160094886616gDZsJ:freedombox.emorrp1.name?via=synapse.sds-ip.de&via=matrix.org&via=freedombox.emorrp1.name)

**Comment by emorrp1** [comment] 2020-09-30 07:53
@bmarty this is still an issue in 1.0.8

**Comment by bmarty** [comment] 2020-10-02 21:40
argh

**Closed** 2020-11-04 12:50 UTC

**Comment by emorrp1** [comment] 2020-11-13 14:09
Happy to confirm for posterity that v1.0.10 now renders correctly, so IRC users can enable /markdown again. Thanks @onurays !
