### ISSUE TITLE
Material Design 3 + Material You

### ISSUE THREAD

**Issue by ThatOneCalculator** [vector-im/element-android#7705] opened 2022-12-05 07:45 UTC
More closely following [Material Design 3](https://m3.material.io/) and possibly adding [Dynamic color (Material You)](https://m3.material.io/styles/color/dynamic-color/overview) would be great. The latest update already adds the square-ish actions buttons which is a step in the right direction :)

**Comment by bmarty** [comment] 2022-12-07 10:07
Duplicate of #3737

**Closed by bmarty** 2022-12-07 10:07 UTC
