### ISSUE TITLE
Space Switching: FAB Cut By Bottom Navigation Bar

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-android#6765] opened 2022-08-08 08:55 UTC
### Steps to reproduce

![IMG_20220808_093818](https://user-images.githubusercontent.com/769871/183379813-c6ca31f2-aeaa-4e95-a2ca-5df79787480b.png)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ericdecanini** [comment] 2022-08-09 08:38
Can you give more context or a screen recording of this happening? I'm unable to reproduce this on my devices

<img src="https://user-images.githubusercontent.com/20701752/183604389-f5418439-aa56-431f-8ab5-9b3603e474cd.png" width="200" />

**Comment by gsouquet** [comment] 2022-08-09 08:41
I don't particularly have clear steps but I often ended up in that state after navigating the app, scrolling up/down, ...
Not sure a screen recording will help very much here

**Comment by ericdecanini** [comment] 2022-08-17 08:44
This issue becomes present when we remove the bottom navigation bar (i.e. when space switching and edit layout are combined). This commit is a quick fix for it, but should be looked at and merged as a separate fix

https://github.com/vector-im/element-android/pull/6842/commits/6ff80d29dc080c9fe1a10fa44f395c602c16768a

**Closed** 2022-08-29 11:26 UTC
Labels: T-Defect, Z-AppLayout
