### ISSUE TITLE
m.room.redaction notification

### ISSUE THREAD

**Issue by 0x1a8510f2** [vector-im/element-android#3413] opened 2021-05-26 13:37 UTC
#### Describe the bug

I occasionally get notifications for `m.room.redaction` events.

#### To Reproduce

[Unsure]

#### Expected behavior

Redactions and other similar events should be ignored

#### Screenshots

![Screenshot_20210526-143432~2.png](https://user-images.githubusercontent.com/83190128/119669158-bab38680-be2f-11eb-87de-6a745cdab364.png)

#### Smartphone (please complete the following information):
 - OS: Stock Android 10

#### Additional context
 - App version: GPlay 1.1.8
 - Homeserver: an-atom-in.space

**Comment by emorrp1** [comment] 2021-06-21 15:07
dupe of #723

**Comment by Florian14** [comment] 2021-07-07 14:49
Closed in favor of #1491

**Closed by Florian14** 2021-07-07 14:49 UTC
