### ISSUE TITLE
Push notifications doesn't work when app is not running in the background.

### ISSUE THREAD

**Issue by fe-dox** [vector-im/element-android#6572] opened 2022-07-17 11:12 UTC
Push notifications doesn't arrive untill the app is opened. Push notifications counter increments correctly.
If the app is in the foreground or is in the background notifications are working correctly, but if the app is closed then they are not arriving at all.

App version: 1.4.27 [40104272] (G-b9527)

**Comment by ownbee** [comment] 2022-07-27 08:44
Same for me. This is one of the most important feature for me since I now "forget" to answer chats when app/android decides to shutdown app. Is there a setting I am missing?

**Comment by g33kex** [comment] 2022-08-02 11:01
I have the same problem as well. As a temporary workaround I use the F-Droid version of the app which doesn't support push notifications so I get the notifications directly. It might consume a bit more battery but at least it works reliably.

**Comment by fedrunov** [comment] 2022-09-01 08:45
Thanks for raising, but unfortunately there is not enough information there for me to be able to reproduce it

there's a few steps that can help troubleshoot this

- Running the Settings -> Notifications -> Troubleshoot Notifications and posting any failing steps here
- Submitting logs via Report bug in the main screen menu
- Allowing Element in any battery saving optimisations

**Comment by bmarty** [comment] 2022-09-12 08:38
I am going to close is as duplicate of #6896.
Please try again with the fixed version Element Android 1.4.36 (will be soon in production)

**Closed by bmarty** 2022-09-12 08:38 UTC
Labels: T-Defect, A-Notifications, S-Major, O-Frequent, X-Needs-Info
