### ISSUE TITLE
Can't log in on custom server

### ISSUE THREAD

**Issue by Koopabro** [vector-im/element-android#5957] opened 2022-05-06 07:27 UTC
### Steps to reproduce

1. Downloaded the app
2. Pressed "I already have an account"
3. Pressed 'other'
4. Typed in my own homeserver
5. Pressed 'next'
6. I get an error 'registration has been disabled'

#### What did you expect?
That I would have the chance to log in

#### What happened instead?
Got a 'registration has been disabled' error

### Your phone model

Pixel 5

### Operating system version

Android 12

### Application version and app store

1.4.13 from Google Play

### Homeserver

Home run synapse server

### Will you send logs?

Yes

**Comment by ouchadam** [comment] 2022-05-06 10:41
thanks for raising, going to close this off as a dupe of #5874  ^^^ the fix is included in 1.4.14 which we're starting to rollout to the beta channel and is also available via the [github releases](https://github.com/vector-im/element-android/releases) like @Toxblh mentions.

as a temporary workaround, if your server has a `.wellknown` setup you should still be able to login via `Sign in with matrix id`

**Closed by ouchadam** 2022-05-06 10:41 UTC
Labels: T-Defect
