### ISSUE TITLE
Very high ram usage (>1 GB)

### ISSUE THREAD

**Issue by mal-tee** [vector-im/element-android#5587] opened 2022-03-19 18:55 UTC
Element eats up very large amounts of RAM in the background, rendering my phone barely useable. 

1.4.2 [40104020] (F-f10c67d3)

F-Droid on Fairphone 3

**Comment by Flam3z** [comment] 2022-03-19 22:30
A new version has been released on f-droid and gplay i suggest updating and see if your issue still persists.

**Comment by F8wuoabTtC** [comment] 2022-03-20 12:18
> A new version has been released on f-droid and gplay i suggest updating and see if your issue still persists.
 
I'm on version 1.4.4 downloaded from f-droid no luck so far! But gplay version seems to be okay but I'm on de-googled android push notifications is a tradeoff!!

**Comment by ouchadam** [comment] 2022-03-21 11:37
thanks for raising :+1:  I'm going to close this as a duplicate of https://github.com/vector-im/element-android/issues/5244 https://github.com/vector-im/element-android/issues/5217

1.4.4 appears to have fixed some of the underlying issues however due to #5244 the fdroid version can still accumulate RAM/storage

**Closed by ouchadam** 2022-03-21 11:37 UTC
