### ISSUE TITLE
Video calls between Android and iOS don't work

### ISSUE THREAD

**Issue by tulir** [vector-im/element-android#2255] opened 2020-10-13 19:08 UTC
**Describe the bug**
Video calls don't work between Element Android and iOS. I'm fairly certain this is not a homeserver or TURN/NAT problem: Audio calls work between Android and iOS with the same devices, users and homeservers. Video calls work between Android and Web, and between iOS and Web. Only Android<->iOS video does not work.

* Calling from Android causes Element iOS to immediately hang up
* Calling from iOS works at first, but accepting that call from Android doesn't work, it just gets stuck in the connecting screen

Riot android issue: vector-im/riot-android#3454
Element iOS issue: vector-im/element-ios#2904

**To Reproduce**
1. Start a video call from Element iOS
2. Answer call on Element Android
3. Call gets stuck in the connection screen

or

1. Start a video call from Element Android
2. Open Element iOS
3. Call immediately hangs up without Element iOS showing it

**Expected behavior**
Video call works between Android and iOS

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro <-> iPhone 8+
 - OS: Android 10 <-> iOS 14.0.1

**Additional context**
 - App version and store: Android G-b375 <-> iOS 1.0.12
 - Homeserver: maunium.net <-> mozilla.org

Logs submitted from both sides with references to this issue.

**Comment by Wodann** [comment] 2020-11-27 03:20
I've been experiencing the same issue.

**Comment by johansmitsnl** [comment] 2021-01-14 21:48
I experience the same issue but sometimes it works but most of the times not. Element web or desktop with iOS works fine.

**Comment by johansmitsnl** [comment] 2021-01-15 18:31
I have to correct my image. On my side it was a missing a good working coturn server. Once configured I have always a good and direct connection. From the synapse admin channel I also found this website to test your turn setup: https://test.voip.librepush.net/

**Comment by m4rkell** [comment] 2021-01-30 20:49
> I have to correct my image. On my side it was a missing a good working coturn server. Once configured I have always a good and direct connection. From the synapse admin channel I also found this website to test your turn setup: https://test.voip.librepush.net/

Hello! Do you win this bug?( I have same problem. Test https://test.voip.librepush.net/ is passed OK, but video calls android<>iphone not work((((

**Comment by johansmitsnl** [comment] 2021-01-31 19:34
It solves calls on the same home server. When one client is at matrix.org and the other on a home server it isn't working yet. So not solved completely yet.

**Comment by m4rkell** [comment] 2021-02-02 14:23
> It solves calls on the same home server. 
How you solves this bug in your server? I have good work coturn, check this in test.voip, but video calls not working android<>iphone (((

**Comment by johansmitsnl** [comment] 2021-02-09 18:19
@m4rkell can you share the test results of https://test.voip.librepush.net/ ?

**Comment by kittykat** [comment] 2021-11-24 12:45
I'm going to close this issue for now as the calls do work now, but there are two issues on iOS that I found during testing which are filed at:
* https://github.com/vector-im/element-ios/issues/5188
* https://github.com/vector-im/element-ios/issues/5189

**Closed by kittykat** 2021-11-24 12:45 UTC
Labels: A-VoIP

**Comment by Wodann** [comment] 2022-01-12 00:32
The particular aspect of this issue that I experienced to be different from the two issues that you liked, @kittykat, is:

> Calling from iOS works at first, but accepting that call from Android doesn't work, it just gets stuck in the connecting screen

The call does connect - causing the incoming call banner to disappear - audio is audible for a fraction of a second, and then it keeps looping on the connecting screen.

**Comment by kittykat** [comment] 2022-01-12 09:02
> > Calling from iOS works at first, but accepting that call from Android doesn't work, it just gets stuck in the connecting screen
> 
> The call does connect - causing the incoming call banner to disappear - audio is audible for a fraction of a second, and then it keeps looping on the connecting screen.

Thank you for following up. We were unable to reproduce this specific issue during testing. Can you please share which versions of Android, iOS and Element apps are being used? Through wifi or mobile data?
