### ISSUE TITLE
Inline images not displayed; replaced with [OBJ] reference

### ISSUE THREAD

**Issue by tophers** [vector-im/element-android#835] opened 2020-01-13 08:56 UTC
Inline images that are displayed on Riot-Web (riot-web version: 1.5.6) are not being displayed in RiotX 0.12.9 G-b1563 on Android. In the place of the expected image is a box with [obj].

**Comment by bmarty** [comment] 2020-01-13 20:57
Could you add a link to such an event from a public room please?

**Comment by tophers** [comment] 2020-01-13 22:04
I don't have a public room to offer -- I've noticed since posting this the current Android Client 0.9.9 (G-5da259a74) does the same thing; although a different icon. The desktop/electron/riot-web client does show the images.  Best I could do is provide screenshots of the same conversation between the two, where riot-web displays the image and the android clients do not if that will be of any help.

**Comment by bmarty** [comment] 2020-01-21 10:10
FTR this is such an event in a non-public room: https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$15792943823271ODXOf:t2l.io

(Note that Riot-Web does not render the image neither)

**Comment by tulir** [comment] 2020-05-04 12:07
Duplicate of #351

**Closed** 2023-01-08 08:11 UTC
