### ISSUE TITLE
QR-codes for faster contact sharing

### ISSUE THREAD

**Issue by totikom** [vector-im/element-android#2025] opened 2020-08-30 21:24 UTC
# The problem
When I want to share a contact (my or someone else's) with the person I've met face to face, I need to spell (or show) my full Matrix ID, which is not very convenient. Otherwise, I can send `matrix.to` link with some external communication method, which is also not very fast.

# Proposed solution
On the "profile page" add "show QR-code" button, which will create QR-code with `matrix.to` link.

![](https://user-images.githubusercontent.com/21067774/91659137-b04da180-ead6-11ea-89d2-4c90cf6cbc6f.jpg)
It will allow users to quickly exchange Matrix IDs, which seems quite usefull.

**Comment by notramo** [comment] 2020-08-31 14:31
It should also do the verification in the same QR code.

**Comment by totikom** [comment] 2020-08-31 15:33
I don't think that it is possible due to the verification protocol. It requires exchange of information in both directions.

**Comment by bahur142** [comment] 2020-08-31 20:04
This will be very useful feature to add someone in the contact list when face-to-face.
 And then adding new contacts can happen like that:

![11](https://user-images.githubusercontent.com/30805725/91763431-4fa98c00-ebde-11ea-9d3c-0ed812f7437d.png)
![12](https://user-images.githubusercontent.com/30805725/91763475-520be600-ebde-11ea-84ad-512b01c1e575.png)

**Comment by ralaud** [comment] 2020-09-01 04:56
May duplicate of #312

**Comment by totikom** [comment] 2020-09-01 08:42
Related but not a duplicate, as I propose _arbitrary contact_ sharing, not just your own.
For example, then I want to recommend one of my fellows to another, I can quickly show him/her the code. Apart from verification process there is no difference between sharing my and someone else's ID.

**Comment by notramo** [comment] 2020-09-03 12:46
@totikom It is possible, although not with the current methods. E.g. the QR code contains a shared secret, and the scanner salts his own key with the secret.

**Closed** 2021-02-28 17:43 UTC
Labels: type:suggestion
