### ISSUE TITLE
Add an option to hide image previews

### ISSUE THREAD

**Issue by tobiasdiez** [vector-im/element-android#6999] opened 2022-09-03 12:11 UTC
#### What would you like to do?

Add an option to show/download an image after the user "accept" it. This exists already for the web version: https://github.com/matrix-org/matrix-react-sdk/pull/3492

#### Why would you like to do it?

This has the benefit of deciding which images you want to see and it can be easier on the data for mobile users.

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2022-09-05 10:15
Duplicate of #6518, closing this one the referenced issue has more info and alternatives.

**Closed by jmartinesp** 2022-09-05 10:15 UTC
Labels: T-Enhancement, S-Minor, O-Uncommon, A-Settings
