### ISSUE TITLE
“Mark message as read” emits new notification

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#782] opened 2019-12-18 22:14 UTC
v0.10.0

When I mark a message as read in the notification drawer of my OnePlus Android 9 device, the following notification, that I have “one unread message”, appears right away:

![Screenshot_20191218-230953__01](https://user-images.githubusercontent.com/10520767/71127783-fe8e6f00-21eb-11ea-8fef-cee6d7e8e7c7.jpg)

**Comment by steef435** [comment] 2019-12-19 09:59
See also #348 (I still experience it as well).

**Comment by lub** [comment] 2020-04-16 10:03
I guess this should be fixed by #1143 ?

**Comment by MatMaul** [comment] 2020-04-16 13:15
It should indeed :)

**Comment by fbruetting** [comment] 2020-04-16 13:56
Let's see hopefully later today. 😜

**Comment by onurays** [comment] 2021-01-19 12:46
Cannot reproduce anymore. Fixed by #1143.

**Closed by onurays** 2021-01-19 12:46 UTC
Labels: bug, feature:notification
