### ISSUE TITLE
Unable to access message and verify users between Android Phones

### ISSUE THREAD

**Issue by bmltp** [vector-im/element-android#3701] opened 2021-07-19 12:47 UTC
#### Unable to access message and verify users between Android phones
I can verify uses and chat by enabling encryption between Any android(Factory Android with google play service + Play store Element app, and GrapheneOS + F-droid element app with iPhone(6 and X)), iPhone with iPhone is also all good.

But between Android Apps(Factory ROMs and GraphaneOS, and their any combination) is giving problem as below:

#### To Reproduce the problem follow as below
1. Install Element on Factory ROM Android from Play Store
2. Install Element on GrapheneOS F-Droid
3. Just try Direct Message(encryption Enabled) and also try to verify user
4. You will see error saying _You cannot access this message_

#### Expected behavior is as below
Start to chat as usual and can verify account

#### Screenshots
Screenshots to help explain your problem.
![Android with play service](https://user-images.githubusercontent.com/58697145/126161445-c0e9abe6-e6f2-4865-b66a-31f5b5e9158f.jpg)
![GrapheneOS + F-droid](https://user-images.githubusercontent.com/58697145/126161465-92e0f567-d957-4738-9be3-22e38c4344d0.jpg)

#### Smartphone details as follow:
 - Samsung J3, Factory ROM Android 5.1.1
 - Pixel 3, GrapheneOS Android 11

#### Both apps and homeserver are recent version as below
 - Play Store app version: 1.1.12
 - F-Droid App version: 1.1.12
 - Homeserver: Synapse version 1.38.0

When When clicked Start verification on any one of these phone request sender just waits, and the verify request receiver phone just says **Encrypted message** Instead of notification to approve or cancel the verify request.

**Comment by popad028** [comment] 2021-07-21 10:10
Same problem with stock firmwares. I tried with 2 Samsung and one Xiaomi.

**Comment by bmltp** [comment] 2021-07-22 06:49
After looking to the @popad028 mentioned [issue number 3687](https://github.com/vector-im/element-android/issues/3687#issuecomment-884272407), I also managed to use verified session between these Android devices by using Element-Desktop to verify. Thanks to [@wioxjk](https://github.com/wioxjk) for this information.

**Comment by BillCarsonFr** [comment] 2021-07-22 14:26
caused by #3725 closing as duplicate thanks for the report

**Closed by BillCarsonFr** 2021-07-22 14:26 UTC
