### ISSUE TITLE
Typing issue 

### ISSUE THREAD

**Issue by thagoat** [vector-im/element-android#7427] opened 2022-10-21 10:09 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
 1. Writing a new mrssage
 2. Entered text, clicked the enter button

#### What happened instead?
Expected a new line
Text was deleted instead

### Your phone model

Motorola 5g ace

### Operating system version

Android 11

### Application version and app store

Google play 1.5.4 [40105042] (G-b12120)

### Homeserver

Synapse home server 

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2022-11-02 08:42
Thanks for reporting! This seems to be a duplicate of #7357. It has already been fixed and will be available when the next app version is published.

**Closed by jmartinesp** 2022-11-02 08:42 UTC
Labels: T-Defect
