### ISSUE TITLE
Incorrectly merged messages

### ISSUE THREAD

**Issue by 0x1a8510f2** [vector-im/element-android#3300] opened 2021-05-07 12:41 UTC
#### Describe the bug
EA usually merges messages by the same person, such that their nickname and avatar are only shown once for a block of messages they wrote, until someone else writes a message or anything else interrupts the block. However, sometimes messages by someone else also get merged with the block (I only noticed it with my own messages thus far). This seems to also survive closing and reopening the room as well as app restarts and cache clears.

#### To Reproduce
1. Have someone write a message
2. Write a message after them
3. Have them write another message
4. If nothing happens, try again*

\* I have not been able to confirm why this happens, so I can't give any more details on how to reproduce this. Sadly, that's not very helpful, but at least you're aware of the issue.

#### Expected behavior
Messages should not be merged unless by the same sender and without anything in between.

#### Screenshots
![image](https://user-images.githubusercontent.com/83190128/117450674-75d7b680-af39-11eb-9cf1-dde42388ac4c.png)
![image](https://user-images.githubusercontent.com/83190128/117450747-90119480-af39-11eb-951c-2c47a0f0b5bb.png)

#### Smartphone (please complete the following information):
 - OS: Android 10

#### Additional context
 - App version and store: gplay v1.1.6
 - Homeserver: an-atom-in.space

**Comment by bmarty** [comment] 2021-05-07 19:05
Thanks for reporting.

This is because there is an edition of another message from the user with the green avatar, which happen just before the message "Can pin it also but I didn't". So EA consider than the previous message (the edition) is from the same user and do not show avatar and display name again.

This is a duplicate of #3184 , fixed for the next release 1.1.7

**Closed by bmarty** 2021-05-07 19:05 UTC

**Comment by 0x1a8510f2** [comment] 2021-05-07 21:19
Awesome. Thanks for explaining and glad to hear it's fixed :3
