### ISSUE TITLE
Images are showing as cropped

### ISSUE THREAD

**Issue by scottwallacesh** [vector-im/element-android#2126] opened 2020-09-18 07:18 UTC
**Description**:
When viewing messages that contain an image from someone else, the image is shown as cropped.  Clearing the cache does not resolve it but does crop your own posted images.  The room(s) are encrypted (I do not know if the same behaviour exists for non-encrypted rooms).  The image appears correctly in element-web.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a message room
2. Post an image on Android device A
3. Use Android device B to view the image in the room - *or* - clear the cache on Android device A and look at the image you posted.
4. Image appears cropped.

**Expected behaviour**
I expect the image to be shown, without being cropped, on Android.

**Screenshots**
Cropped on Element Android:
![image](https://user-images.githubusercontent.com/290593/93567731-a228cd80-f97e-11ea-9dda-a0d71872623c.png)

Not cropped on Element web:
![image](https://user-images.githubusercontent.com/290593/93567484-3c3c4600-f97e-11ea-83d6-eb3436a625cb.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11

**Additional context**
 - App version and store: v1.0.6 from Google Play Store
 - Homeserver: Self-hosted Synapse v1.19.2

**Comment by jtrees** [comment] 2020-09-20 08:37
I get this too and I'm on matrix.org.

**Comment by onurays** [comment] 2020-10-13 08:09
@scottwallacesh, @jtrees I couldn't reproduce this issue on my devices and emulators (I also tried on Pixel 2 Emulator, running Android 11). Could you please send me the original image through Element Android room or DM (@onurays:matrix.org)?

**Comment by jtrees** [comment] 2020-10-16 12:18
I think this was fixed in Element 1.0.7. I presume it was fixed with https://github.com/vector-im/element-android/pull/2108.

**Closed** 2020-11-19 16:29 UTC
Labels: bug, screen:timeline
