### ISSUE TITLE
User data is "über alles" -- voice message over 2 min is just dropped.

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#4023] opened 2021-09-16 04:33 UTC
### Steps to reproduce

Try to record a long voice message. It will be deleted as soon as it will become longer than 2 minutes.

### What did you expect?

Actually I expect a possibility to record voice messages without limitation.

### What happened

But this issue is not about voice messages. It it about one of the main principles that all software should follow: user data is infinitely valuable.

### Operating system version

Android 11

### Application version and app store

1.2.2 from GPlay, beta channel

### Have you submitted a rageshake?

No

**Comment by ouchadam** [comment] 2021-11-25 11:16
thanks for raising and I completely agree :+1: 

I'm unable to reproduce this error, this may have been fixed in a later version, when hitting the 2 minute limit the recording can still be sent.
 
going to close, feel free to reopen if I've misunderstood the scenario

**Closed by ouchadam** 2021-11-25 11:16 UTC
Labels: T-Defect, A-Voice-Messages

**Comment by 532910** [comment] 2021-11-25 12:48
It looks like this has been fixed. Can confirm voice records exceeding the limit are not dropped more.
