### ISSUE TITLE
Bug / Reply format broken when too many new lines|ws? in <mx-reply>

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#153] opened 2019-05-27 16:26 UTC
This displays correctly

`<mx-reply><blockquote><a href=\"https://matrix.to/#/!ybTPiZFJfZqybWGFeU:matrix.org/$1558973971435611GBlYs:matrix.org\">In reply to</a><a href=\"https://matrix.to/#/@valere35:matrix.org\">@valere35:matrix.org</a><br /><p>copy cou</p>\n</blockquote></mx-reply>ok
`

But not this:

`<mx-reply>\n              <blockquote>\n                <a href=\"https://matrix.to/#/!ybTPiZFJfZqybWGFeU:matrix.org/$1558973683434084MSYOS:matrix.org\">In reply to</a>\n                <a href=\"https://matrix.to/#/@valere35:matrix.org\">@valere35:matrix.org</a>\n                <br />\n                <p>Bonjour</p>\n\n              </blockquote>\n            </mx-reply>\n            salut
`
<img width="234" alt="image" src="https://user-images.githubusercontent.com/9841565/58431167-dc48ce80-80ac-11e9-9794-78b6366fd135.png">

**Comment by tulir** [comment] 2019-07-13 17:38
Caused by #350 (RiotX uses a markdown parser for HTML rendering) and would technically be fixed by #174 (RiotX doesn't render replies properly, but instead just displays the fallback)

**Comment by dud1337** [comment] 2022-02-01 15:46
This can be closed

**Closed** 2022-10-05 13:01 UTC
Labels: T-Defect

**Comment by kittykat** [comment] 2022-10-05 13:02
@dud1337 thank you for going through and commenting on issues which have been resolved. If you come across any more that need closing, please feel welcome to tag me in your comment so that I get notifications!
