### ISSUE TITLE
unreadable font colour when using "follow system design"

### ISSUE THREAD

**Issue by svenb1234** [vector-im/element-android#2792] opened 2021-02-07 13:39 UTC
**Describe the bug**
When using "follow system design", i.e. automatically switch between dark and bright design, the font becomes unreadable, when the design is switched. The font colour seems to remain instead of also switch. After some hours, the font colour changes eventually.

**To Reproduce**
1. Go to settings > settings > design
2. Enable system default
3. Set android to change the design automatically from dark to bright
4. Wait for a design change

**Expected behavior**
The design within element should switch (works) including a change of the font colour (does not work)

**Screenshots**
Will be supplied after the next switch.

**Smartphone (please complete the following information):**
 - Device: pixel 4a
 - OS: android 11
 - element version 1.0.16

**Comment by svenb1234** [comment] 2021-02-07 17:21
![Screenshot_20210207-181329-01](https://user-images.githubusercontent.com/46424536/107154067-2ea94c00-6971-11eb-89ed-63f9ba800ab6.jpeg)

Font colour after android automatically switched to the dark design and elemt tried to follow.

**Comment by bmarty** [comment] 2021-02-08 15:01
Yes, this is a know issue, but thanks for reporting. After theme switch, kill and restart the app should fix the problem

**Comment by ryanhagen** [comment] 2021-02-12 18:04
Also have the same issue, this happened immediately after i turned off dark theme this morning.
![Screenshot_20210212-100014](https://user-images.githubusercontent.com/6934612/107804987-8d781800-6d19-11eb-8967-d1143aa17c05.png)

**Comment by bmarty** [comment] 2021-04-20 12:47
Duplicate of #2738

**Closed by bmarty** 2021-04-20 12:47 UTC
