### ISSUE TITLE
set profile picture

### ISSUE THREAD

**Issue by steef435** [vector-im/element-android#1021] opened 2020-02-15 21:38 UTC
Would be nice if we could crop the picture as well. Maybe this could reuse some of the attachment process code?

**Comment by bmarty** [comment] 2020-02-15 21:42
Yes, when it will be merged :)

**Comment by lub** [comment] 2020-07-21 21:43
Seems like #1590 is a duplicate of this.

**Comment by bmarty** [comment] 2020-08-20 14:46
Set profile picture is now supported let's keep only #1590 open then

**Closed by bmarty** 2020-08-20 14:46 UTC
