### ISSUE TITLE
New messages don't appear

### ISSUE THREAD

**Issue by claudemontreal** [vector-im/element-android#8128] opened 2023-02-14 13:15 UTC
New messages are not appearing, I have to force kill the app and restart it for the new messages to load.

I thought it good be a battery optimization issue, but turning it off for Element didn't change anything.

**Comment by kittykat** [comment] 2023-02-15 14:31
Hi, can you please fill in the [details requested in the bug template](https://github.com/vector-im/element-android/issues/new?assignees=&labels=T-Defect&template=bug.yml)? Unfortunately we don't have enough information about your system to start investigating this issue as we cannot reproduce it.

**Comment by kittykat** [comment] 2023-02-15 15:04
Duplicate of #8137

**Closed by kittykat** 2023-02-15 15:04 UTC
Labels: T-Defect, A-Timeline, S-Critical, O-Uncommon, X-Needs-Info
