### ISSUE TITLE
Cross-Signing for Element-Android requested even though already verified

### ISSUE THREAD

**Issue by TheJJ** [vector-im/element-android#1391] opened 2020-05-20 17:50 UTC
I got a verification request from some user who uses Element-Web/Desktop and wanted to accept it on Element Android. Element Android then said that the current session **"is not cross-signed"** and I should verify the login on an existing session or enter the recovery key.

As it is not a new session and it should be cross-signed already, there is no verification popup in Element-Web, so just to test, I entered the recovery key on the apparently unverified Element-Android. The key was accepted and showed the green shield.

After this, the user sends another account verification request, and the same thing repeated from the beginning, that my "session is not verified yet". So the cross-signing-procedure just before apparenly didn't verify anything.

On my Element-Web instance, this Element-Android-client _is_ marked as verified and trusted!

**Comment by AluisioASG** [comment] 2020-07-17 23:37
I think I'm seeing a similar issue. The session is verified but private cross-signing keys are not known and I can't set up key backup.

**Comment by fri-sch** [comment] 2020-08-23 18:30
I installed Element and verified it successfully through the existing RiotX session. Everywhere the new session is shown as verified, but when I try to setup the backup in Element, I still get the verification screen as if the session was not verified yet. I'm stuck here and need to find a way to setup the backup.

**Comment by TheJJ** [comment] 2020-11-21 15:48
After some static debugging and infering state from looking at the UI messages etc I think the reason for this to happen is that:

```
info.isCrossSigningTrusted == false
```
reason: the UI displays "Set up on this device" under "Secure Backup", but megolmSecretKnown probably true

```
checkSelfTrust.isVerified() == true
```
since `encryption_information_dg_xsigning_complete` is displayed due to
```
session.cryptoService().crossSigningService().canCrossSign() == true
# implemented as:
checkSelfTrust().isVerified() &&
   cryptoStore.getCrossSigningPrivateKeys()?.selfSigned != null &&
   cryptoStore.getCrossSigningPrivateKeys()?.user != null
```

hence to `isCrossSigningTrusted` to become false,  `liveCrossSigningInfo(session.myUserId).isTrusted() == false`.
```
-> MXCrossSigningInfo::masterKey()?.trustLevel?.isVerified() == true
&& MXCrossSigningInfo::selfSigningKey()?.trustLevel?.isVerified() == true
```

Either the master or the selfsigningkey seems to be not verified on the device. I'm trying to debug further.

**Comment by kittykat** [comment] 2022-08-31 12:22
I'm still experiencing an issue which looks like this one

**Comment by kittykat** [comment] 2022-08-31 13:01
Duplicate of #4931

I'm going to close this issue for now in favour of a newer one about the same problem.

**Closed by kittykat** 2022-08-31 13:01 UTC
Labels: A-E2EE, A-E2EE-Cross-Signing
