### ISSUE TITLE
Spaces name shows after logging out and into other account

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#3415] opened 2021-05-26 16:29 UTC
#### Describe the bug
I logged out of my account and into another account. In the top bar under "Direct Messages" I see a space I joined in the old account.

#### To Reproduce
1. Log in to main account
2. Open a space so the top bar says the space name
3. Log out and into the other account

#### Expected behavior
The space name should not show as I am not part of it in the other account.

#### Additional context
 - App version and store 1.1.8 play store

**Comment by bmarty** [comment] 2021-05-31 19:13
@BillCarsonFr can you investigate please?

**Comment by kittykat** [comment] 2022-01-07 11:58
@timokoesters can you still reproduce the issue? I haven't been able to over here so wanted to check with you before closing

**Comment by kittykat** [comment] 2022-01-21 14:14
I'm going to close this issue for now as we cannot reproduce it. If anyone can, please comment with @kittykat and I will re-open it.

**Closed by kittykat** 2022-01-21 14:14 UTC
Labels: T-Defect, A-Spaces, S-Critical, X-Needs-Info, X-Needs-Community-Testing
