### ISSUE TITLE
Persistent toast asking to verify, but no sessions need verifying

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4287] opened 2021-10-21 12:40 UTC
### Steps to reproduce

This was found during the Android testing on October 21

"After verifying, I have a persistent toast(?) coming down from the top asking me to review where I'm logged in with a scarry red shield. It covers the UI so I can't use the app right away and when I click on it, it showns me that all my other sessions are verified with green shields."

"After verifying it asks to check my other sessions (with a red exclamation mark). It looks like I should do something, but I don't know what I should check there, and why. It seems ok there (no unverified sessions)"

#### What did you expect?
When being told I need to verify a session, the app should show me the sessions that need verifying. 
It would also be good to have a less intimidating message

#### What happened instead?
Intimidating message showed red exclamation mark but all shields are green

### Will you send logs?

No

**Comment by kittykat** [comment] 2022-08-31 12:16
Duplicate of #https://github.com/vector-im/element-android/issues/4318

**Closed by kittykat** 2022-08-31 12:16 UTC
Labels: T-Defect, A-E2EE, S-Minor, O-Occasional, Z-Community-Testing
