### ISSUE TITLE
Beta 0.91.4, Speakerphone is not used for ringback tone

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#1644] opened 2020-07-08 01:30 UTC
When video calling somebody, the ringing tone at the originator end is not through the speakerphone. Instead the ringing tone comes through the phone/'ear piece'.

Also incoming rings stimulate the 'ear piece' rather than the 'speakerphone'. There is a bluetooth watch connected to the phone.

**Comment by rajil** [comment] 2020-07-08 06:13
Seems like duplicate of [#1644](https://github.com/vector-im/riotX-android/issues/1644)

**Comment by bmarty** [comment] 2020-07-08 07:10
@rajil duplicate of itself? :)

**Comment by pvagner** [comment] 2020-07-23 09:55
When incoming audio call is ringing it's playing through ear piece for me.
When incoming video call is ringing it's playing through loud speaker here.
I'd like if incoming audio call also rrang through the loud speaker.

**Closed** 2020-09-11 14:18 UTC
Labels: feature:call
