### ISSUE TITLE
New App Layout: filter label "Favourites" smaller font size

### ISSUE THREAD

**Issue by twouters** [vector-im/element-android#7088] opened 2022-09-10 13:03 UTC
### Your use case

The font size of the filter labels differs. This probably to make the labels fit, but it might be better to keep the size equal?

![Screenshot_20220910-145538](https://user-images.githubusercontent.com/170895/189484576-43d5eed4-b711-462f-83fe-92151c679f67.jpg)

### Are you willing to provide a PR?

No

**Comment by fedrunov** [comment] 2022-09-12 07:26
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-android/issues/6816

**Closed by fedrunov** 2022-09-12 07:26 UTC
Labels: T-Enhancement, Z-AppLayout
