### ISSUE TITLE
Integration manager broken on Android

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-android#8392] opened 2023-05-03 13:43 UTC
### Steps to reproduce

1. Try to add an integration to a Room
2. Wait for page to load

#### What did you expect?

Ability to modify and add integrations

#### What happened instead?

The page says my device isn't supported, while android app claims this is a stable feature.

### Your phone model

One Plus 7 Pro

### Operating system version

Android 12

### Application version and app store

Element Version 1.5.32 [40105322] (G-8dcb5f70), Matrix-SDK-Version: 1.5.32 (8dcb5f70), Olm Version: 3.2.12

### Homeserver

Synapse 1.80.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by MTRNord** [comment] 2023-05-03 13:44
The rageshake was sent prior to this hence missing a mention of this issue.

**Comment by Florian14** [comment] 2023-05-05 07:21
Thanks for the report, I reproduced the issue. We'll investigate.

![image](https://user-images.githubusercontent.com/11990514/236398463-26d4ded7-e865-421d-b25d-d182c80009a7.png)

**Comment by Florian14** [comment] 2023-05-16 12:05
I close this issue since it should be fixed by https://github.com/vector-im/element-android/issues/7893

**Closed by Florian14** 2023-05-16 12:05 UTC
Labels: T-Defect, A-Integrations, S-Major, O-Frequent

**Comment by demmm** [comment] 2023-05-19 14:34
Why is this closed?  The linked PR has been open since January and no action on it since February.  Will this even be merged? Or are other options considered to fix this issue?
