### ISSUE TITLE
VoIP proximity sensor not working?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#1861] opened 2020-08-02 12:22 UTC
"The proximity sensor does not work during an audio call, the smartphone display does not go out during the call" on Xiaomi redmi S2

**Comment by BillCarsonFr** [comment] 2020-08-03 12:53
Yes it's not implemented yet, has been descoped. will be added ssoon

**Comment by kittykat** [comment] 2021-11-17 16:52
I'm going to close this issue as it's been fixed for 1.3.8 and we cannot reproduce it any more

**Closed by kittykat** 2021-11-17 16:52 UTC
Labels: A-VoIP, T-Enhancement
