### ISSUE TITLE
Text does not disappear from input field when sharing from another app

### ISSUE THREAD

**Issue by faaaaabi** [vector-im/element-android#2350] opened 2020-11-06 09:31 UTC
**Describe the bug**
If I share text content from another app over its share functionality, the text shared does not disappear from the input field after sending. If I clear the input field manually to send a new message, the new message reappears in the input field. When I then put the App in background and re-enter it over its app icon, everything is fine.

**To Reproduce**
1. Share any Text/Link via another app with a room in element-android
2. Click send an see the shared text not disappearing from the input field
3. Clear the input field manually enter a text manually and send it
4. See your manually entered text reappear in the input field

**Expected behavior**
The input field should clear it self after sending a message in the context of sharing text content from another app

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro, Samsung Galaxy S8
 - OS: Android 10, Android 9

**Additional context**
 - App version 1.0.9 Playstore
 - Homeserver:  self hosted syanpse v1.20.1

**Comment by dipeve** [comment] 2020-11-06 22:05
Duplicate of #2287

**Closed** 2020-11-08 14:22 UTC
