### ISSUE TITLE
Sent message stuck at the bottom of the chat despite sending hours ago.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#1055] opened 2020-02-23 23:23 UTC
Version Info: 0.16.0

Device: Samsung S10
![Screenshot_20200223-182232_RiotX](https://user-images.githubusercontent.com/57234536/75122233-a0f22500-5669-11ea-8b6f-d967bfc9a290.jpg)

**Comment by aquatix** [comment] 2020-04-25 11:05
I also have this issue, with a message that keeps getting stuck as latest sent, while it was sent in March.

**Comment by fbruetting** [comment] 2020-04-28 11:27
Duplicate of #516 ?

**Comment by aquatix** [comment] 2020-04-28 11:34
Looks like it, yes. Thanks for the reference!

**Comment by bmarty** [comment] 2020-11-10 22:08
Should be fixed now (Element 1.0.10), please re-open if it's not the case

**Closed by bmarty** 2020-11-10 22:08 UTC
Labels: performance
