### ISSUE TITLE
Uploading a file to a room caused it to have a info.size of -1

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-android#2141] opened 2020-09-20 13:56 UTC
The file itself was fine, but the info is wrong. The file was uploaded via the sharing feature from another app.

```json
{
  "content": {
    "body": "2020-09-20 14:17.kmz",
    "file": {
      "hashes": {
        "sha256": "teCKsNkRVo5VAxZu9+/CSbd1V9psNTjbEEeXRJxvUCE"
      },
      "iv": "49Ra2xgOSs8AAAAAAAAAAA",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "B6xVPtphPdn3NPttOAWmxsjcCC9pUWrTIoFyjZ-ySPw",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "mimetype": "application/vnd.google-earth.kmz",
      "url": "mxc://half-shot.uk/3194e07c835b6d4fc3430606f7fdf19fc76a68f9",
      "v": "v2"
    },
    "info": {
      "mimetype": "application/vnd.google-earth.kmz",
      "size": -1
    },
    "msgtype": "m.file"
  },
  "room_id": "!vHHXZqTuzXCuldIVQJ:half-shot.uk",
  "type": "m.room.message"
}
```

**Comment by onurays** [comment] 2020-10-14 11:13
I am closing the issue because it is only reproducible on @Half-Shot's main account.

**Comment by bmarty** [comment] 2020-10-14 13:56
To reproduce:
- download OpenTracks from https://f-droid.org/en/packages/de.dennisguse.opentracks/
- Using this app create a new record
- Share the record to any room (e2e or not) of Element Android

**Closed** 2020-10-16 15:05 UTC
Labels: bug, feature:upload
