### ISSUE TITLE
Reactions appear cut off

### ISSUE THREAD

**Issue by Throlo** [vector-im/element-android#5149] opened 2022-02-03 19:31 UTC
![Screenshot_20220203-161812_Element_1](https://user-images.githubusercontent.com/82319992/152414699-f968568d-270c-44a1-b2b0-da16a5b50673.jpg)

The reactions appear cut off regardless of whether it is a room or a direct chat.

**Comment by kojid0** [comment] 2022-02-09 23:20
Cannot reproduce. Your emoji looks way bigger than mine. What font size did you select in settings?

**Comment by kojid0** [comment] 2022-02-10 12:50
> "Largest"

Alright, can reproduce now. Looks like the button doesn't resize along with the other elements.

**Comment by ganfra** [comment] 2022-02-22 09:54
Closed by #5204

**Closed by ganfra** 2022-02-22 09:54 UTC
Labels: A-Reactions, A-Emoji, Z-Papercuts, S-Tolerable, O-Occasional
