### ISSUE TITLE
Annoying notification in a direct discussion that I'm give a call

### ISSUE THREAD

**Issue by jpggithub** [vector-im/element-android#2472] opened 2020-11-30 20:41 UTC
**Describe the bug**
In a direct discussion with a friend (so just him and me are member of the room) :

**To Reproduce**
1. Go to a direct discussion with a friend
2. Call him
3. You receive a notification that you are calling him

It's annoying and not useful at all.

**Expected behavior**
I don' want receive a notification when I call someone.

**Smartphone
 - Samsung S4
 - OS: Lineage  17.1. Android 10.0
- Element 1.0.11 (fdroid, without gapps)
- on matrix.org

**Comment by kittykat** [comment] 2021-11-17 16:43
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat if you can still reproduce it in v1.3.8 (coming out next week)

**Closed by kittykat** 2021-11-17 16:43 UTC
Labels: A-VoIP
