### ISSUE TITLE
break share files with element

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#7489] opened 2022-10-31 08:10 UTC
### Steps to reproduce

1. Go to the gallery
2. choose a photo to send
3. click share
4. choose element
5. in element select the desired room
6. this room opens and that's it (without the photo sending dialog)
7. turn the phone on its side - a dialog for sending a file will appear
8. click send
9. rotate back to portrait orientation - another file upload dialog will appear - press cancel

If you do not turn the phone on step 7, then the files are not sent.

element andriid 1.5.4 gapps

### Your phone model

OnePluse 8t

### Operating system version

Android 12

### Application version and app store

element andriid 1.5.4, olm 3.2.12 gapps

### Homeserver

rsprim.ru

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by cyphar** [comment] 2022-10-31 15:53
This also happens when trying to share links to Element. This was broken very recently, I believe in the 1.5.4 update (from memory the issue wasn't present in 1.5.2 but I can't downgrade the app to double-check at the moment, so might be wrong). I'm using standard Android on the Pixel 4a.

**Comment by BlastyCZ** [comment] 2022-10-31 20:38
Same behavior - android 13
I'm pretty sure problem occured after last update

**Comment by DanielGibson** [comment] 2022-11-01 15:53
I'm observing the same problem on a Samsung A33 with Android 12, also pretty sure it appeared in 1.5.4, whatever version I had before the update (from Google Appstore) worked as expected.

**Comment by ThiefMaster** [comment] 2022-11-01 20:12
This is a major problem, quick fix would be appreciated...


...because I don't appreciate the "are you still on skype since I can't send you pictures here" messages from my family members who I moved to matrix/element a few years ago ;)

**Comment by ThiefMaster** [comment] 2022-11-01 20:19
ah, this seems to be a duplicate of #7400

**Comment by jmartinesp** [comment] 2022-11-02 08:42
> ah, this seems to be a duplicate of #7400

Yes, good catch. Closing this as it should be fixed for the next release. Thanks for reporting!

**Closed by jmartinesp** 2022-11-02 08:42 UTC
Labels: T-Defect
