### ISSUE TITLE
Voice call button is missing in room with only 2 participants (threads are disabled)

### ISSUE THREAD

**Issue by zeronymous** [vector-im/element-android#5875] opened 2022-04-29 13:19 UTC
Element version: 1.4.11 [40104110] (F-aec19656) from F-Droid

In a room with myself and only one other person, the voice call button is not present on the Android client.  Only the video call button is present. 
The threads feature is not enabled.  
For reasons I don't understand, this conversation is classified as a "room" and not a "direct message" (i.e. it is found under the "#" tab) but checking the room settings shows there are only 2 participants, and access is private.  The other participant in the room is using the iOS client and has a call button which they can use to start a voice call with me, but lacking the button, I am unable to initiate one with them.

**Comment by ouchadam** [comment] 2022-05-27 09:48
Thanks for raising! this is _technically_ the correct behaviour for a group/room chat as we only show the call option for direct messages. More information can be found in https://github.com/vector-im/element-android/issues/5779 and the linked conversations.

The issue (like you've hinted at) is caused by the direct message being considered a room by the app, a workaround is to use the command `/converttodm` in the affected chat in Element Web.

I'll close this issue in favour of https://github.com/vector-im/element-android/issues/3333

**Closed by ouchadam** 2022-05-27 09:48 UTC
