### ISSUE TITLE
video preview at videocall break after change phone orientation

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#1599] opened 2020-07-02 02:38 UTC
1. start videocall
1. change portrait to album orientation
1. see only part of sended video-stream at preview window
1. change orientation to portrait - situation not changed
1. tap on preview window - change camera from front to rear - preview is ok
1. tap again to change to front camera - preview is ok

change to album:
![Screenshot_20200702-122728](https://user-images.githubusercontent.com/1297163/86310002-5fe5cf00-bc60-11ea-81f8-ea164321184d.png)
bad portrate:
![Screenshot_20200702-122735](https://user-images.githubusercontent.com/1297163/86309986-59575780-bc60-11ea-8012-a82d12da6a88.png)

switch to rear - help:
![Screenshot_20200702-122758](https://user-images.githubusercontent.com/1297163/86309976-53fa0d00-bc60-11ea-891a-95837f6b7771.png)

return to front - is good:
![Screenshot_20200702-122817](https://user-images.githubusercontent.com/1297163/86309961-4ba1d200-bc60-11ea-8503-5426ffcc9a05.png)
Andoid 6.0
phone: Yotaphone2
RiotX version 0.23.0-dev [40023001] (G-b3059)

**Comment by rajil** [comment] 2020-07-02 08:10
I tried this on Android 7.0 with Beta Riot 0.91.3 and cannot reproduce this.

**Comment by progserega** [comment] 2020-09-11 05:00
I check in 1.0.6 - video orientation of preview changed after change orientation of phone, but with ~20 sec timeout after changing orientation of phone.

**Comment by kittykat** [comment] 2021-11-17 16:58
I'm going to close this issue as it's been fixed in 1.3.8 :+1:

**Closed by kittykat** 2021-11-17 16:58 UTC
Labels: A-VoIP
