### ISSUE TITLE
New call timeline is redundant

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2586] opened 2020-12-26 19:44 UTC
Screenshot in #2517
Why is the profile picture and name needed in **each tile**? It's a DM after all.
It should simply display:
- incoming/outgoing
- duration
- call state

**Comment by violoncelloCH** [comment] 2020-12-26 19:48
I think it'd make sense for groups to see who initiated andmparticipated in a call (once this will be possible in matrix natively) but it's indeed redundant information for 1-1 / DM chats

**Comment by notramo** [comment] 2020-12-26 19:55
And groups don't have calls yet, only Jitsi widgets.
And it's certainly about DMs.

**Comment by ariskotsomitopoulos** [comment] 2021-11-17 17:00
I will close this issue, duplicate of https://github.com/vector-im/element-android/issues/2955

**Closed by ariskotsomitopoulos** 2021-11-17 17:00 UTC
Labels: A-VoIP
