### ISSUE TITLE
[Voip] : Other call not always refreshed when ended

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#4028] opened 2021-09-16 16:52 UTC
### Steps to reproduce

1. Launch 2 different calls in 2 rooms.
2. Let the opponent of the held call hangups

### What did you expect?
The held call should disappear completely from UI (Active call views, InCall screen)
### What happened?
The held call is still shown in Active call views and InCall screen. It disappears when you close the screens.

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment] 2021-11-17 16:30
I'm going to close this issue for now as we were unable to reproduce it in a community testing session. Please re-open if it's still valid.

**Closed by kittykat** 2021-11-17 16:30 UTC
Labels: T-Defect, A-VoIP
