### ISSUE TITLE
Unable to upload .apk files

### ISSUE THREAD

**Issue by arunsathiya** [vector-im/element-android#1428] opened 2020-05-30 14:52 UTC
It is not possible to upload `.apk` files on the latest version of the Riot X app. This was my first time trying to upload one, so, I am unsure if it worked in the previous versions of the app. 

The upload seemingly starts, but in the end, ends up failing and the message text appears in red.

The same `.apk` file upload works on Riot desktop on Mac.

**Comment by bmarty** [comment] 2020-06-04 10:16
Thanks for reporting, we will test that

**Comment by onurays** [comment] 2020-10-01 11:51
We reimplemented the Media Picker. I just tested and couldn't reproduce anymore, so I am closing the issue.

**Closed by onurays** 2020-10-01 11:51 UTC
Labels: feature:upload
