### ISSUE TITLE
Swipe right from anywhere to open quick room switcher and spaces menu

### ISSUE THREAD

**Issue by tactical-snail** [vector-im/element-android#5527] opened 2022-03-12 11:10 UTC
### Your use case

The quick room switcher that opens when you swipe right from the left corner of the screen in a chat room, and the hamburger menu in the home screen, both should open on swiping right from anywhere, or atleast from the middle of the screen, not just the left corner.

The room switcher is a great feature but swiping from the corner triggers android back gesture. And stretching your finger to the hamburger menu everytime for switching between spaces isn't convenient.

**Comment by ericdecanini** [comment] 2022-03-14 21:45
@daniellekirkwood could this potentially be classed as a papercut?

**Comment by kittykat** [comment] 2022-03-28 14:55
I'm going to close this as a duplicate of #3852

**Closed by kittykat** 2022-03-28 14:55 UTC
Labels: T-Enhancement, Z-Papercuts, X-Needs-Product
