### ISSUE TITLE
If media cache is large, Settings > General takes a long time to open

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#5918] opened 2022-05-03 19:10 UTC
### Steps to reproduce

1. Have a large enough media cache. 100+ MB was enough for my device. Others might need a larger cache.
2. Open the General menu in Settings. Note the time it takes to open the menu.
3. Clear media cache.
4. Open the menu again. Note the drastically reduced time taken for it to open.

#### What did you expect?

The menu should open just as fast as other menus do. And it should take roughly the same time to open on every try.

#### What happened instead?

With a large enough media cache, the menu takes a long time to open (~5-10 seconds).

A wild guess is that the app doesn't open the menu until it has calculated the media cache, which can take a long time if the cache is large enough, or if the device is old, with slow I/O.

### Application version and app store

1.4.11 (F-Droid)

### Will you send logs?

No

**Comment by jcgruenhage** [comment] 2022-05-25 14:35
Sounds related to, or even like a duplicate of, #5665 to me, and I'm also experiencing this issue, as are a few others I've talked to. Also: this makes the magic CC&R workaround I regularly need due to #5212 a bit worse, as I have to first clear the cache in Androids settings, and then in Element itself.

**Closed** 2023-02-07 13:03 UTC
Labels: T-Defect, A-Performance, S-Minor, O-Occasional, A-Settings
