### ISSUE TITLE
Custom SSO + login with android and IOS

### ISSUE THREAD

**Issue by alpha856** [vector-im/element-android#6831] opened 2022-08-14 21:55 UTC
Hello, is it possible to use custom SSO with matrix synapse and element mobile versions?
I have read that element maybe does not support SSO login now.

**Comment by ouchadam** [comment] 2022-08-15 11:04
there may have been a misunderstanding, SSO can still be used to login or register using Element however there's a specific regression where a homeserver which relies on an empty `identity provider` configuration will not be offered an SSO sign in button due to https://github.com/vector-im/element-android/issues/6827

going to close this as a duplicate of https://github.com/vector-im/element-android/issues/6827

**Closed by ouchadam** 2022-08-15 11:04 UTC
