### ISSUE TITLE
Update `Direct Messages` and `Rooms` headers from UI

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#4533] opened 2021-11-21 09:35 UTC
#### What would you like to do?

Remove the `Direct Messages` and `Rooms` expandable headers from the DMs and Rooms tabs respectively.

#### Why would you like to do it?

It is annoyingly frequent that I accidentally tap the header and hide the chat list when I'm intending to open the top chat.

Moreover, I don't see the point of these headers. Not only are they buggy (switching the tab and switching back expands them again), but seemingly redundant. The title bar of the app already tells you which tab you have opened. The headers seem to have been copied from the Element Web UI directly, without an actual use case. 

The only expandable header that makes sense is `Invites`, because you might get a lot at once, and want to hide them so you can focus on your existing chat list.

#### How would you like to achieve it?

I would like to see the 2 headers removed completely. The `Invites` header can have a distinctly visible UI boundary so that it's clear when the invites end and the existing DMs/Rooms start.

## Solution

Based on our chat, here is the proposed solution. The changes I have made are:
- Created a band under collapsible /expandable headers
- Added no. of items in the list (similar to ios)
- Changed type style of header to make it clearer

![Screenshot 2021-12-14 at 19 55 01](https://user-images.githubusercontent.com/85162587/146070791-555e6b38-945c-4a20-bb85-737f0ffe7e89.png)

Link to Figma file: https://www.figma.com/file/QugKzfgL4gISlsmluw9EVb/Change-expandable-headers?node-id=4%3A2593

Also, sections should only appear here if they have items in them.

**Comment by bmarty** [comment] 2021-11-22 13:55
FTR: there are other possible headers: "favorites", "Low priority" and also "System alert". Depending on the tab, the sections are built here: https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt#L75

**Comment by opusforlife2** [comment] 2021-11-22 20:47
Thanks. I just realised there is a long press menu for the chat list.

How about checking if there are any chats in the `Favourites` or `Low priority` categories, and choosing not to display the DM and Room headers if there are zero such chats? The headers could be created the moment a chat is added to either of the categories.

These two seem like the 'permanent' or 'long-term' categories. `Invites` and `System alert` will tend to be addressed within a much shorter time frame, so I don't think they will be as much of an issue.

**Comment by ouchadam** [comment] 2021-12-06 13:31
when I first used element I found it a bit strange that the title items were collapsible, I would have expected that UX on menus or expanding text to show more information  

I would be interested to know if many users would understand why their messages are missing in this scenario

![2021-12-06T13:30:24,574330992+00:00](https://user-images.githubusercontent.com/1848238/144854605-3f49a320-dfe0-412b-8d5d-78be60cbc1aa.png)

**Comment by daniellekirkwood** [comment] 2021-12-06 16:17
### Meeting Notes
- The headers feel like navigation, should they be collapsible at all, or just separate tabs?
- Collapsing Invites and Low Priority is well used and should stay
- Visually, they could have better treatment
- What are the web IA changes and how would they impact this?
- Favourites needs to be collapsible because they're stuck to the top of the screen regardless of whether it was the most recent messages
- Each section has a badge associated, so if a Low Priority room has an unread message then you'll struggle to find it with a long Rooms list
- If a section is empty, it does not show in the list

### Next steps
- [ ] Discuss longer term IA changes with Delight team @daniellekirkwood 
- [ ] Keep Invites, Favourites, Low Priority, System Alerts as expand and collapse but continue to discuss removing Expand/Collapse for All DMs or All Rooms sections
- [ ] Quick visual fixes to be proposed by @amshakal, including looking at tappable areas

### Questions
- [ ] If there's only one section, can we remove the header altogether?

**Comment by amshakal** [comment] 2021-12-14 20:00
Based on our chat, here is the proposed solution. The changes I have made are:
- Created a band under collapsible /expandable headers
- Added no. of items in the list (similar to ios)
- Changed type style of header to make it clearer

![Screenshot 2021-12-14 at 19 55 01](https://user-images.githubusercontent.com/85162587/146070791-555e6b38-945c-4a20-bb85-737f0ffe7e89.png)

Link to Figma file: https://www.figma.com/file/QugKzfgL4gISlsmluw9EVb/Change-expandable-headers?node-id=4%3A2593

**Comment by daniellekirkwood** [comment] 2022-01-06 16:07
I have updated the content of the issue with the feedback from Amsha and removed the Needs-Design and Needs-Product label as this issue is now Ready to be built.

**Comment by mnaturel** [comment] 2022-02-02 13:06
Hi! I would to like to fix this issue but I don't clearly understand what should be done in term of UX. For UI, it seems okay since there is a link to Figma. Can someone sum up the expected behavior (visibility, expandable or not?, etc.) about the header sections depending on the different cases ?

**Comment by daniellekirkwood** [comment] 2022-02-02 14:54
@mnaturel Heya! 
- All sections should be expandable/collapsible
- Sections are only visible if they have content

@amshakal to confirm

**Comment by amshakal** [comment] 2022-02-03 13:07
^ Just what @daniellekirkwood said

**Comment by bmarty** [comment] 2022-02-04 09:59
That's fine, but what @daniellekirkwood has said is already implemented no?

**Comment by mnaturel** [comment] 2022-02-04 14:44
Hello @amshakal @daniellekirkwood, when editing UI headers as specified, I have realized we already have a red notification counter as well (see capture below). Are you aware of this notification counter (it does not appear on the Figma screens) ? 
In my opinion, with this design, it may be confusing for some users about the meaning of each counters.

<img width="361" alt="4533-header" src="https://user-images.githubusercontent.com/46314705/152547339-9b1a8ae6-6fa0-4c20-8b73-2b7dccf06799.png">

So my questions are:

- Is the number of items counter really needed ?
- If this counter is really needed, should we stay with the same design ?

**Comment by amshakal** [comment] 2022-02-07 11:43
Hi there, thanks for working on this. The rationale to keep the counter is so that users know there are items under that list if the section is collapsed, there could be a scenario where the user thinks there is nothing inside that section otherwise. This also helps us have parity with iOS.

The main change we were proposing was to make the headers more prominent (with a grey band and with a more distinctive text style)

Was aware of the notification badge - didn't account for it in the designs since the behaviour wasn't changing. I believe the colour of the badge should be grey or red based on the type of notification they receive?

**Comment by mnaturel** [comment] 2022-02-07 12:50
Okay, thanks for the reply. Yes the badge is indeed either red or grey.

**Comment by amshakal** [comment] 2022-02-07 12:53
Another thing we can do to avoid users getting confused by different numbers is move notification badge to the right to match notification (unread counter) per room

Ref: https://github.com/vector-im/element-android/issues/4640

**Comment by mnaturel** [comment] 2022-02-07 12:59
It is a good idea! I will try moving it to the right to see how it renders.

**Comment by mnaturel** [comment] 2022-02-09 13:55
Hi @amshakal , I have implemented the required changes. Can you review if the design is correct? I have added some screenshots in https://github.com/vector-im/element-android/pull/5181. Also, ask me if you need to see the behavior of the app.

**Closed** 2022-03-14 12:51 UTC
Labels: A-Room-List, T-Enhancement, Z-WTF, Z-Ready
