### ISSUE TITLE
Reaction shows up as +2 in the timeline

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6531] opened 2022-07-13 09:13 UTC
### Steps to reproduce

1. In a room, add a new reaction to a message
2. See reaction count increase by 2

#### What did you expect?
Reaction count is at 1

#### What happened instead?
Reaction count is at 2

### Operating system version

Android 11

### Application version and app store

1.4.27

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2022-07-13 19:47
I have seen it, but I do not repro systematically. Thanks for having created the issue.

**Comment by bbhtt** [comment] 2022-07-16 09:16
I think this is same as/or related to https://github.com/vector-im/element-android/issues/5795

**Comment by ouchadam** [comment] 2022-08-18 14:29
lets close as a duplicate of #5795

**Closed by ouchadam** 2022-08-18 14:29 UTC
Labels: T-Defect, A-Reactions, S-Minor, O-Occasional
