### ISSUE TITLE
Notifications notify more than once

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6260] opened 2022-06-08 09:10 UTC
### Steps to reproduce

1. Receive a DM, phone buzzes with a notification
2. Phone keeps buzzing every ~1-5 minutes and a bell appears next to the time since the notification first appeared. There are no new notifications as far as I can see

#### What did you expect?
Phone buzzes once for a new DM message and keeps showing the new message notification on the screen

#### What happened instead?
Phone keeps buzzing as if there are other new notifications, but I can't see any new ones.

### Operating system version

Android 11

### Application version and app store

1.4.16 [40104162] (G-b8288)

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by erikjohnston** [comment] 2022-07-25 10:22
I get this quite regularly. Is there anything I can do when it happens to help track it down? (I'm using nightly)

**Comment by richvdh** [comment] 2022-08-03 16:39
sounds related to https://github.com/vector-im/element-android/issues/6167

**Comment by ouchadam** [comment] 2022-08-08 13:48
Priority raised as notifications are flagged as chronic issues

**Comment by kittykat** [comment] 2022-08-09 10:40
FYI, this issue is still persisting for me and it's affecting my phone battery because if I leave my phone out of earshot and receive a DM, then it keeps vibrating every few seconds to minutes until my phone battery is drained.

Note that I'm having issues with exactly the same DMs that I talked to Adam about a few months ago where I wasn't receiving any notifications. I wonder if the fix for that created this issue?

**Comment by ouchadam** [comment] 2022-08-09 11:06
my current theory is that something is triggering unnecessary pushes to the device (which in turn wakes it up), such as read receipts or activity in muted rooms

**Comment by richvdh** [comment] 2022-08-09 14:04
> my current theory is that something is triggering unnecessary pushes to the device (which in turn wakes it up), such as read receipts or activity in muted rooms

at least in my case, the problem is not unnecessary pushes (each message in a silent room is *supposed* to cause a push) but rather that my phone bings/vibrates on every push.

**Comment by kittykat** [comment] 2022-10-21 08:42
I'm going to upgrade this issue to "Occasional" as some people (like me) are experiencing it every day

**Comment by septem9er** [comment] 2023-06-27 12:25
Could someone please have a look at this issues? It's open for a year and it is really annoying and impacting battery life.

My Element constantly rings, sometimes multiple times a minute, just because of a single unread message in a chat which isn't muted. That's simply unacceptable. I had to completly mute the app now, which is obviously impacting the UX as well, because I _do_ want to get notified for some chats.

**Comment by richvdh** [comment] 2023-06-27 12:53
Duplicate of #6167

**Closed by richvdh** 2023-06-27 12:53 UTC
Labels: T-Defect, A-Notifications, S-Critical, O-Occasional, Z-GetYourUpdates, Z-Chronic

**Comment by aminomancer** [comment] 2024-06-18 10:41
Is it certain this is a duplicate? I see this bug repeatedly for a year or so, but #6167 does not sound familiar to me at all.
