### ISSUE TITLE
App Layout: Recents don't set to zero (you have to scroll left)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6851] opened 2022-08-16 16:02 UTC
### Steps to reproduce

Found in testing today:

Shows up in recents, but at the left partially off-screen on second device | 
Follow the test case. Screenshot: https://i.k8r.eu/3zi2Rw.png (note small part of the room at the left of the recents)

Recents should start at zero, there should be rooms to scroll left to until the user initiates scroll

I think there was already an issue for this but I can't find it, so raising again

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by gsouquet** [comment] 2022-09-01 11:14
Duplicate of https://github.com/vector-im/element-android/issues/6776

**Closed by gsouquet** 2022-09-01 11:14 UTC
Labels: T-Defect, Team: Delight, Z-AppLayout
