### ISSUE TITLE
add a "Skip" button to verify login

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#4737] opened 2021-12-16 10:15 UTC
### Steps to reproduce

Not sure, here are some bad cases:

If I'm not next to my web session: https://photos.app.goo.gl/JdznmtRyZJvewxm7A
if it's not popping up on web: https://photos.app.goo.gl/5U6KB84NvYzPyqXa7

### Outcome

This skip button should have the same functionality as clicking on "This wasn’t me" button and then on settings and the back button.
Explained better in the video:
https://photos.app.goo.gl/rkS3TA2pHJLtX7k27

### Your phone model

Xiaomi Pro 8

### Operating system version

Android 12

### Application version and app store

private fork

### Homeserver

private server

### Will you send logs?

No

**Comment by ouchadam** [comment] 2021-12-21 12:04
thanks for providing extra information! going to close this as a dupe of https://github.com/vector-im/element-android/issues/4025

**Closed by ouchadam** 2021-12-21 12:04 UTC
Labels: T-Defect
