### ISSUE TITLE
Screen stays on permanently (until manually shut off) on all devices that didn't answer the call

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-android#2205] opened 2020-10-03 01:15 UTC
This issue has been happening for months, so it's happening in the current version and has been around for a long while.

I have Element setup on multiple android devices, desktops and laptops. When I receive a voice or video call to my account, I could answer it from many different places.

For android devices, however, if I have an android device that did not pick up that call, Element will keep the screen on and show the screen as if a call is still coming in. It will prevent the screen from ever turning off, even if it is covered by a magnetically triggered cover, or similar. This can entirely drain the device till death.

Really oughta get this one fixed.

**Comment by ralaud** [comment] 2020-10-04 11:31
Related to #1921

**Comment by onurays** [comment] 2020-11-11 10:16
I couldn't reproduce this anymore. https://github.com/vector-im/element-android/pull/2058 merged 9 days ago and should solve the problem. Could you please test it on v1.0.10?

**Comment by bmarty** [comment] 2020-11-16 14:53
Please re-open the issue if it can be reproduced on 1.0.10

**Closed by bmarty** 2020-11-16 14:53 UTC
Labels: bug, feature:call

**Comment by ralaud** [comment] 2020-11-18 17:13
I think this need to be re-opened.

**Describe the bug**
Account from Phone A is also logged in Element-web 1.7.13. If I call Phone A with Phone B and cancel the call every device is closing the call notification, but if I accept the call in Element web, the call notification on Phone A will not be closed.

The most interesting part is, if I have accepted call **_with microphone_** input in Element-web, everything is working fine. But if I accept the call **_without microphone_** input in Element-web then I have still an ongoing notification on Phone A.

**To Reproduce**

1. Open Element-web (Account from Phone A) without microphone input
2. Call Phone A with Phone B
3. Accept call in Element-web 
4. Still an ongoing notification on Phone A

**Expected behavior**
Notification on Phone A need to be closed automatically if I accept call in Element-web (even if I have no microphone input).


**Smartphone (please complete the following information):**
 - Device: -
 - OS: Both Phones; Android 10

**Additional context**
 - App version and store: Both Phones; 1.0.10 - F-Droid
 - Homeserver: matrix.org

Best regards!
