### ISSUE TITLE
Unable to decrypt messages

### ISSUE THREAD

**Issue by ghost** [vector-im/element-android#3687] opened 2021-07-17 22:58 UTC
#### Describe the bug
Accounts created using the mobile client on two different devices cannot access the messages of each other or complete verification.

#### To Reproduce
1. Create two accounts on different devices through the Android client.
2. Invite and accept the invitation for direct messaging.
3. Send a message.
4. On the receiving device, see error `Unable to decrypt: KEYS_WITHHELD` in developer mode.

#### Smartphone (please complete the following information):
 - Device: Xiaomi Redmi Note 9, Redmi Note 8T
 - OS: LineageOS 18.1, Android 10

#### Additional context
 - App version and store 1.1.12 - F-Droid, 1.1.12 - Play Store
 - Homeserver: self hosted

**Comment by popad028** [comment] 2021-07-21 10:50
Confirm, i have the same problem. Also there is another opened issue https://github.com/vector-im/element-android/issues/3701

**Comment by wioxjk** [comment] 2021-07-21 15:16
I confirm that I and other contacts of me have the same issue.
Opening up the same chat on a PC seems to solve the problem for that particular chat

**Comment by BillCarsonFr** [comment] 2021-07-22 14:26
caused by #3725 closing as duplicate thanks for the report

**Closed by BillCarsonFr** 2021-07-22 14:26 UTC
Labels: bug, 🔥 fire
