### ISSUE TITLE
[VoIP] Echo from loudspeaker during call

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#3390] opened 2021-05-21 14:00 UTC
#### Describe the bug

Observed when having a call between two Element-Android devices. Enabling the loudspeaker causes the other person to hear an echo of their own voice, and vice-versa.

#### To Reproduce
1. Call from Element-Android on Device1.
2. When user on Device2 picks up, either or both then switch audio to loudspeaker.
3. Either one or both hear an echo of their own voice.

#### Expected behavior

No echo when using the loudspeaker.

#### Smartphone (please complete the following information):
 - Device: multiple devices
 - OS: multiple OSs

#### Additional context
 - App version and store: 1.1.7 - F-Droid & Play Store
 - Homeserver: matrix.org, fairydust.space

**Comment by HarHarLinks** [comment] 2021-11-17 16:24
I can reproduce this:
In a p2p call between myself and another element android, the other can use loudspeaker without problem, but the other side informs me that I am producing terrible echo, so I have to use headphones.

Version Schildichat 1.3.6.sc47-test4 F-Droid

**Comment by kittykat** [comment] 2021-11-17 16:26
I can't reproduce it on a Pixel 2 in a call with Danielle on 1.3.8. @HarHarLinks could you [try it with 1.3.8](https://github.com/vector-im/element-android/releases/tag/v1.3.8) please?

**Comment by ouchadam** [comment] 2021-11-17 17:06
I was able to reproduce on 1.1.16 but not 1.3.8 this might simply be because the newer versions of element android have reduced the maximum loud speaker volume (which in turn improves the accuracy of the OS's echo cancellation)

**Comment by ouchadam** [comment] 2021-12-14 09:56
going to close this issue, if we're able to reproduce on 1.3.8+ we can reopen

**Closed by ouchadam** 2021-12-14 09:56 UTC
Labels: T-Defect, A-VoIP, S-Major, O-Occasional, X-Needs-Info
