### ISSUE TITLE
Strip EXIF from uploaded JPEGs by default to preserve privacy.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#1353] opened 2020-05-10 15:26 UTC
matrix-org/matrix-react-sdk#1307 implements this for Riot Web; Android should also by default strip GPS info from uploaded images.

(We could also strip out the EXIF rotation metadata at this point and put it in the event itself, so that clients displaying the image can rotate appropriately)

twinned with https://github.com/vector-im/riot-ios/issues/3230

**Comment by Atrate** [comment] 2020-05-10 15:35
If RiotX won't strip all EXIF data by default (e.g. just GPS) then it would be nice to have a switch that would allow the user to have RiotX strip ALL EXIF data.

**Comment by violoncelloCH** [comment] 2020-05-10 18:18
I feel like this is a duplicate of #465 ... I also already posted some ideas about how to implement a "option" to send the original image with all exif data without adding settings or checkmarks wich are complex (tbh confusing for the average user who doesn't really care about what EXIF is)...

also related: #978 (rotation metadata)

**Comment by auscompgeek** [comment] 2020-06-08 14:48
> (We could also strip out the EXIF rotation metadata at this point and put it in the event itself, so that clients displaying the image can rotate appropriately)

This one seems like a bad idea, since then when you save a copy of the image it'd have the wrong rotation.

**Comment by starcraft66** [comment] 2020-07-05 18:18
Please make this optional.

**Comment by bmarty** [comment] 2020-09-04 12:28
Dup of #465

**Closed by bmarty** 2020-09-04 12:28 UTC
