### ISSUE TITLE
Disappearing Messages similar to the Signal messaging app.

### ISSUE THREAD

**Issue by gitr0n1n** [vector-im/element-android#2691] opened 2021-01-17 22:03 UTC
**Is your feature request related to a problem? Please describe.**
Disappearing Messages similar to the Signal messaging app. It is a pain to manually delete messages. An auto purge method after x days/weeks would be great for server resources and privacy.

**Describe the solution you'd like**
Implement Disappearing Messages similar to the Signal messaging app.

**Describe alternatives you've considered**
None, this is straight forward and should be a default feature.

**Additional context**
review a great implementation of this feature in this app: https://www.signal.org/

Related Issues:
https://github.com/matrix-org/synapse/issues/6287
https://github.com/vector-im/element-web/issues/3800
https://github.com/vector-im/element-web/issues/16187
https://github.com/vector-im/element-ios/issues/3948
https://github.com/vector-im/element-android/issues/2691

Dated Issue:
https://github.com/vector-im/element-web/issues/2497

**Comment by SimonBrandner** [comment] 2021-01-18 06:57
Duplicate of [#2497](https://github.com/vector-im/element-web/issues/2497)

**Comment by SimonBrandner** [comment] 2021-01-18 07:00
Duplicate of #747

**Comment by kittykat** [comment] 2021-12-29 11:16
Duplicate of vector-im/element-meta/issues/82

Thank you, we appreciate that you took your time to file this enhancement request. I am going to close it for now in favour of a cross-platform issue to help us track the request more effectively.

**Closed by kittykat** 2021-12-29 11:16 UTC
Labels: T-Enhancement
