### ISSUE TITLE
Reactions are lost on old events

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4280] opened 2021-10-20 15:35 UTC
- Send an Event
- Add reaction(s) on it
- Send lots of other events, restart the app, wait a few days, not sure what are the minimal path here
- Scroll back to the first event

Observe that the reaction(s) has vanished

Major since reactions are not reliable

**Comment by ganfra** [comment] 2021-10-20 15:44
It's probably because of timeline chunk merging when back paginating (has to be confirmed).
If so, should be fixed by the started rework of chunks handling

**Closed** 2022-01-03 19:20 UTC
Labels: T-Defect, A-Reactions, S-Major, O-Frequent
