### ISSUE TITLE
Display name is case sensitivity, registration fails 

### ISSUE THREAD

**Issue by akallabeth** [vector-im/element-android#5099] opened 2022-01-31 07:00 UTC
Linked issues:
https://github.com/vector-im/element-ios/issues/5664

When building out this screen in FTUE we should ensure that the keyboard defaults to lower case letters, and has field level error message for real-time updates.

<hr>

### Steps to reproduce

I´ve helped a friend register a new account which failed with a strange error.

1. Where are you starting? What can you see?
Registration of new user. Phone autocorrect did capitalize the first letter

2. What do you click?
Register new user 

After correcting the capital first letter the registration succeeded.

#### What did you expect?
Registration complete

#### What happened instead?
Strange looking error code

### Your phone model

Samsung, not sure which exact model

### Application version and app store

Latest from play store as of last saturday (28.01.2022)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment] 2022-01-31 20:21
I quickly tested the user story with Element 1.3.17:
- create an account on matrix.org using displayname *Benoit010101*. Note that on my phone, there is no capitalization of first letter for this field, and this is the expected behavior.
- the account *@benoit010101:matrix.org* is created. Note that the `B` has become `b`

So I have not reproduced the issue.

Can you provide more details or a screenshot about the strange error you have seen?

**Comment by akallabeth** [comment] 2022-02-01 08:47
@bmarty sorry, no. As mentioned, did help a friend who could not register and was astonished about this too.
will not be able to get that particular phone in my hands for quite some time and don´t have any phone with google tools installed myself.

**Comment by daniellekirkwood** [comment] 2022-03-04 14:34
Investigating this issue with the team yesterday and found that the issue is with the username, not display name and also that in the case of SSO there's unlikely anything that we can do. 

Due to those things I'm going to close this issue and we'll track the keyboard info as a part of the deliverable for [this issue here](https://github.com/vector-im/element-meta/issues/128) which is actively being worked on.

**Closed by daniellekirkwood** 2022-03-04 14:34 UTC
Labels: T-Defect, Z-FTUE, X-Needs-Info, Z-WTF, A-Signup
