### ISSUE TITLE
Edit immediately, without waiting for sending to complete

### ISSUE THREAD

**Issue by haadr** [vector-im/element-android#1760] opened 2020-07-20 14:15 UTC
The title really says it all. Currently, when I want to edit a message immediately after sending (typo), I first have to wait until the message has completed sending before I have to long-press again and then edit.

Would it be possible to queue the edit request for when the sending is complete? Or possibly abort and update the sending request? At the very least, I'd expect to be able to edit the message when sending is complete without having to exit the long-press menu and long-press the message again.

Thanks for reading!

**Comment by TR-SLimey** [comment] 2020-07-20 15:26
Should be able to cancel not sent messages also without developer mode.

**Comment by bmarty** [comment] 2020-08-05 20:18
This is a duplicate of #190

**Closed by bmarty** 2020-08-05 20:18 UTC
