### ISSUE TITLE
"Sorry, but managing extensions isn't supported on this device" message appears when trying to add widget integrations

### ISSUE THREAD

**Issue by suzdaleva** [vector-im/element-android#8571] opened 2023-07-04 11:43 UTC
### Steps to reproduce

1. Go to any chat room.
2. Click on a dot menu, select "Add Matrix apps".
3. See screen loading for a few seconds, then loading fails with the message "Sorry, but managing extensions isn't supported on this device. We're working on it...".

### Outcome

Expected behavior
App allows users to manage widget integrations. As far as I understand, there used to be a way to create a new widget with a link or edit/delete existing widgets.
![Screenshot_2023-07-04-13-02-06-469_de spiritcroc riotx debug](https://github.com/vector-im/element-android/assets/82533889/059217a5-c9f7-4b36-b4c5-b835c9cd2594)

Actual behavior
Clicking on "Add Matrix apps" on the menu inside a chat room results into an error with the message "Sorry, but managing extensions isn't supported on this device. We're working on it..."

### Your phone model

Xiaomi M2004J19C

### Operating system version

Android 10.0

### Application version and app store

1.6.3

### Homeserver

https://matrix.org/

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2023-07-11 13:46
Duplicate of https://github.com/vector-im/element-android/issues/7893

**Closed by bmarty** 2023-07-11 13:46 UTC
Labels: T-Defect

**Comment by sscanavini** [comment] 2025-03-06 09:22
Version 1.6.32 of the app and still having this problem.
