### ISSUE TITLE
Image in HTML Message not displayed

### ISSUE THREAD

**Issue by lomion0815** [vector-im/element-android#1531] opened 2020-06-22 21:38 UTC
When a message contains a HTML tag '<img'> with src point to a mxc URI the image is displayed correctly in RiotWeb. RiotX only display a small OBJ icon. According client-server specification the img tag is allowed.

**Comment by lub** [comment] 2020-06-25 11:57
Seems like a duplicate of #351

**Closed** 2023-10-09 07:57 UTC
