### ISSUE TITLE
allow user certificates on android

### ISSUE THREAD

**Issue by b8c16** [vector-im/element-android#4253] opened 2021-10-15 12:21 UTC
On older Android (e.g. 7.0) devices no connection to homeserver using LE certificates with new LE root certificates in chain is possible (SSL failure).
Android user can install new LE root certificates in android's user certificate store but element-android do not use this user store obviously. Configuration in network_security_config.xml trust-anchors
Therefore please enable (or provide an option to) use of user certificates. Otherwise the missing option bricks the phone.

**Comment by opusforlife2** [comment] 2021-10-30 21:19
@ouchadam https://github.com/syphon-org/syphon/pull/384/commits/b4202ba20e78d34881c794cd2dd391c0e342c406

**Comment by ouchadam** [comment] 2021-11-01 10:20
> Is there a way to enable debug logging on a fresh install? Before you connect to a server, you can't get to preferences to enable this...

that's a very good point... at the moment locally running a development build is the only way, I'll create an issue

> @ouchadam [syphon-org/syphon@b4202ba](https://github.com/syphon-org/syphon/commit/b4202ba20e78d34881c794cd2dd391c0e342c406)

maybe a _hot take_ (and my own personal opinion), I would argue it's not the responsibility of clients of a system to maintain external certificates  

with that said... the change is quite small, if we can show that peoples certificates are setup correctly and they're still having the issues I would have no issues with pinning the DST Root CA for android 7.0 and below

----

Before making any client changes I'd like to first confirm that anyone with the issue on android 7.0 and below is using a homeserver which provides the cross signed root CA

```
openssl s_client -showcerts -connect your.home.server:443 
```

```
Certificate chain
 0 s:CN = your.home.server
   i:C = US, O = Let's Encrypt, CN = R3

 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1

 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

**Comment by opusforlife2** [comment] 2021-11-01 16:03
@ouchadam Had a friend with an Android 7.0 device try this command with the homeserver `fairydust.space`. The output correctly shows `DST Root CA X3`, but Element on that device cannot connect to the server when trying to log in with it. It says `Unable to find homeserver`. Just to be sure, that device has the DST root cert in the system cert store.

**Comment by ouchadam** [comment] 2021-11-01 16:41
not sure why yet but its seem there's something fishy going on in the different sign in flows when it comes to _trusting_



with the DST CA X3 cert disabled on a nexus 4 running 5.1.1 I'm able to reproduce the homeserver not found error via the `sign in with matrix id` flow but `other` is working fine...

Sign in with matrix id 

| | | 
| --- | --- |
|![CA-disabled-2](https://user-images.githubusercontent.com/1848238/139706127-7d8f7988-38bf-4b23-9429-d59106a55702.png)|![unable-to-find](https://user-images.githubusercontent.com/1848238/139706136-42d8d197-5d54-4c39-b700-46391da1b540.png)


Other flow

| | | | | |
| --- | --- | --- | --- | --- |
![Screenshot_20211101_163255](https://user-images.githubusercontent.com/1848238/139707231-a3de80a0-7b57-4906-a5aa-7edb3f908eec.png)|![Screenshot_20211101_163304](https://user-images.githubusercontent.com/1848238/139707226-6c7516ca-7ef3-41aa-ab6b-d733192b4dae.png)|![Screenshot_20211101_163312](https://user-images.githubusercontent.com/1848238/139707225-11c1a567-698a-4258-aff3-8bf610be787a.png)|![Screenshot_20211101_163333](https://user-images.githubusercontent.com/1848238/139707223-52153c5f-8917-4fc3-b727-a679bf7ded46.png)|![Screenshot_20211101_163352](https://user-images.githubusercontent.com/1848238/139707643-ece8499f-2c22-4e6e-9427-8e38dd750834.png)

**Comment by opusforlife2** [comment] 2021-11-01 16:47
@ouchadam So a bug in Element after all?

**Comment by ouchadam** [comment] 2021-11-01 18:22
diffing the certs from my server, `envs.net` and `fairydust.space` it looks like fairydust is using a `ecdsa` cert which is specially incompatible with android 7.0 due to a bug in android https://issuetracker.google.com/issues/37122132 :sweat_smile:  

https://community.letsencrypt.org/t/any-info-on-the-upcoming-ecdsa-certificate-chain-with-android-compatibility/149613/3

to ensure the highest compatibility with android the home server should create `RSA ` certificates instead of `ecdsa`

left `fairydust.space`, right `envs.net`
![2021-11-01T18:08:47,877852845+00:00](https://user-images.githubusercontent.com/1848238/139721190-f7e650e5-c71c-42dd-ad7a-c9b8c3c36ca4.png)

**Comment by ouchadam** [comment] 2021-11-01 18:31
I'm happy to get in touch with them :100: will also look to update any home server hosting FAQs with all the information we've gathered so far

**Comment by ouchadam** [comment] 2021-11-02 11:54
To sum up the let's encrypt considerations 

- For compatibility with Android 7.0 and below it's recommended to use the Default Chain with RSA keys
- Android 7.0 and below support is currently set to expire September 2024
- Android 7.0 only is incompatible with ECDSA P-384 keys

https://community.letsencrypt.org/t/production-chain-changes/150739
https://community.letsencrypt.org/t/any-info-on-the-upcoming-ecdsa-certificate-chain-with-android-compatibility/149613/4
https://issuetracker.google.com/issues/37122132

To confirm the home server certificate is compatible run `openssl s_client -showcerts -connect your.home.server:443 ` and check that the `DST Root CA X3` is part of the chain and the signature type is `RSA` or use a service like https://www.ssllabs.com/ssltest/index.html

Going to close this issue, if we have reports with compatible certificates we can reopen

**Closed by ouchadam** 2021-11-02 11:54 UTC
Labels: X-Cannot-Reproduce

**Comment by docsteel** [comment] 2021-11-02 11:55
This issue also affects Android 9 and 10. What's the Solution for this Version?

**Comment by ouchadam** [comment] 2021-11-02 12:06
This issue is specific to to combination of home servers using the Let's encrypt certificate and a matrix client running on Android 7.0 and below.

Android 7.1.1 and above by default include the ISRG Root X1 certificate authority in the system CAs so there's no benefit to including the ISRG Root X1 CA within element as it's already present on the system.

If we're seeing issues with other android versions lets open another issue as it will have a different cause (I'm assuming this is the `unable to find a home server` error?)

@docsteel if you're able to reproduce the issue any additional information would be super helpful :pray:

**Comment by MacLemon** [comment] 2021-11-07 17:17
Hi!
I'm one of the fairydust.space Cabin Crew.

To put this in perspective: To the best of our knowledge, this issue seems to affect a single device of a single account of our total user base.
Noone on our team has a device that we could use to reproduce the issue ourselves. So trying to add support for that device it is trial and error without any guarantee that it will eventually work.

We're looking into supporting hybrid certificates, meaning ECC *and* legacy RSA certificates which may or may not remedy the issue.

**Comment by xpac1985** [comment] 2021-11-07 17:28
Not sure if this of any help, but our issue could be solved by using a less strict SSL cipher list, maybe @docsteel can share the exact change. I cannot exactly explain why that solved the issue, but it was seemingly related to the latest LetsEncrypt cert renewal...

**Comment by MacLemon** [comment] 2021-11-07 17:34
What's your cipherstring at the moment?

**Comment by docsteel** [comment] 2021-11-07 21:46
SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1

SSLCipherSuite 'ALL:!RSA:!CAMELLIA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SHA1:!SHA256:!SHA384'

**Comment by mackerel225** [comment] 2024-06-04 11:23
Hosting synapse on web server locally and attempting to connect to it without adding certs to smartphone works, but it throws warning message. If I enforce client certificates, then its 'SSL Error'

lighttpd config
```
    ssl.verifyclient.activate = "enable"
    ssl.verifyclient.enforce = "enable"
```
