### ISSUE TITLE
Proximity sensor works after call finished

### ISSUE THREAD

**Issue by szewdev** [vector-im/element-android#2467] opened 2020-11-28 16:20 UTC
**Describe the bug**
Proximity sensor is still enabled after the call ends. 

**To Reproduce**
1. End VoIP call
2. Hide sensor with your hand 
3. Screen gets black
4. Have to uninstall app (killing process is not enough) to dis ale proximity sensor 

**Expected behavior**
Disable proximity sensor after call finished

**Comment by kittykat** [comment] 2021-11-17 17:16
I'm going to close this issue as the proximity sensor is actually disabled during video calls and we cannot reproduce the issue. The issue may be hardware specific so if you're still seeing it, please reply with @kittykat and more information, and I will be happy to re-open it for you :+1:

**Comment by 532910** [comment] 2021-11-17 21:18
Video calls weren't the problem. Proximity sensor should be used during an audio call, and it's not released every time. It doesn't happen every time and it's hard to reproduce.

**Comment by Luciogi** [comment] 2021-12-14 10:16
This issue is still produce-able on my device (Redmi 9t) [release 1.3.9], but not on other device (Honor 9c). 
I have sent bug reports within application.
Can you make an option in setting that will let user to enable or disable proximity sensor during call ?
@kittykat

**Comment by kittykat** [comment] 2021-12-14 10:25
@Luciogi I see two rageshakes (log submissions through the app) which I believe are yours. One is from v1.3.7 three days ago and another from v1.3.9 two days ago. Is that correct?

I have attached both to this issue, and put the issue onto the team's triage board so it can be prioritised and investigated.

**Comment by Luciogi** [comment] 2021-12-14 10:35
I have sent latest bug report also include that , may be reports you mentioned could not be mine.

**Comment by ouchadam** [comment] 2021-12-15 17:22
I have a suspicion this is caused by us always attempting to acquire wake locks and not checking if we already have one, will raise a tentative fix

https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/call/CallProximityManager.kt#L96

**Comment by bmarty** [comment] 2021-12-15 20:23
Fixed in EA 1.3.11

**Closed** 2021-12-15 20:23 UTC
Labels: T-Defect, A-VoIP, S-Major, O-Uncommon
