### ISSUE TITLE
Cache is getting a leaking issue

### ISSUE THREAD

**Issue by syboxez** [vector-im/element-android#8048] opened 2023-01-31 17:00 UTC
### Steps to reproduce

This will take time to reproduce. Over the course of about 2-3 months of consistently using Element (Android), the app data (not the Android cache, but labeled as app data) will grow to several gigabytes and the program will become so unresponsive that it is basically unusable.

After it grows, the app seems to automatically clear the caches and resync messages. This process repeats every 2-3 months.

Manually clearing cache in the app settings (not in Android settings) will also temporarilly fix the issue.

#### What did you expect?
A more minimal data storage solution that doesn't store anything that it doesn't need to store. The app should also never need to automatically clear caches in the way that it is now.

#### What happened instead?
App data grows to several gigabytes over time and then erases itself (not including verification cross-signing/megaolm keys)

This bug has been in Element for as long as I remember, and only recently did the app start clearing its own caches after growing to several gigabytes

### Your phone model

Oneplus 6, Nexus 6P, Pixel 3a

### Operating system version

Android 9, 10, 11, 12, and 13

### Application version and app store

F-Droid 1.5.20, but this is a very old bug

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Florian14** [comment] 2023-03-03 08:52
@bmarty Looks like we did some cache-related changes, could these changes have fixed this issue?

**Comment by jmartinesp** [comment] 2023-05-26 13:15
Possibly a duplicate of https://github.com/vector-im/element-android/issues/2620 (which seems to be fixed for some users)?

Since we didn't get a reply we'll close the issue. Please re-open it if the problem is still there for you.

**Closed by jmartinesp** 2023-05-26 13:15 UTC
Labels: T-Defect, S-Critical, O-Uncommon
