### ISSUE TITLE
Sign in with matrix ID should check for SSO too

### ISSUE THREAD

**Issue by olmari** [vector-im/element-android#4053] opened 2021-09-21 22:16 UTC
#### What would you like to do?
When selecting "Sign in with matrix ID" Element-android should check for SSO-login on server immediately instead only password login
#### Why would you like to do it?
So user don't need to explicitly go do more than needed?
#### How would you like to achieve it?
Make sign in with matrix ID screen immediately check for SSO (or generally login options) through .well-known when MXID is entered,

### Have you considered any alternatives?

Even more powerful would be to copy the current Element-web login screen logic in broad general, it is much more on-point and does what needed when needed, including .well-known check when entering MXID, and immediately offering login options available for user.

**Comment by bmarty** [comment] 2021-09-28 12:12
Yes, I agree, we are working to improve Login Flow, and this particular use case will be improved. Here is how the UX will look like:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/3940906/135084255-766f0e9e-0112-46f0-9584-5bbb82d8f83a.png">

**Comment by bmarty** [comment] 2021-09-28 12:29
Also this is a duplicate of #2122

**Closed by bmarty** 2021-09-28 12:29 UTC
Labels: type:registration, T-Enhancement
