### ISSUE TITLE
Implementing discussion bubbles in Element

### ISSUE THREAD

**Issue by Regia2** [vector-im/element-android#1805] opened 2020-07-24 16:11 UTC
The vast majority of consumer messaging applications such as Signal, Telegram or WhtasApp have this functionality. 
It's a feature that the people around me are asking for a lot; speech bubbles make conversations "warmer". 
And this aspect, I think, is very important to take into account if Element wants to appeal to a large audience ! 
Without bubbles, Element is a little bit repulsive to the labda user who finds bubble-free conversions too "professional" or "geeky"...

**Comment by duncanturk** [comment] 2020-07-25 10:22
I think it's a duplicate of #979

**Comment by kittykat** [comment] 2021-09-03 14:24
Closing because this is a duplicate of #979

**Closed by kittykat** 2021-09-03 14:24 UTC
Labels: feature-proposal, bubbles
