### ISSUE TITLE
Double notification when receiving call

### ISSUE THREAD

**Issue by LinAGKar** [vector-im/element-android#3400] opened 2021-05-24 06:15 UTC
#### Describe the bug
When you are receiving a voice call, two notifications pop up. One is the event notification from the chat saying a call was started, and the other is the incoming call notification where you can accept or decline. The former seems redundant. 

#### Smartphone (please complete the following information):
 - Device: Oneplus 8T
 - OS: Android 11

#### Additional context
 - App version and store 1.1.7 [40101072] (G-b2298) Google Play
 - Homeserver: Self hosted

**Comment by kittykat** [comment] 2021-11-17 16:38
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat if you are still seeing the issue in v1.3.8 (coming out next week).

**Closed by kittykat** 2021-11-17 16:38 UTC
Labels: A-Notifications, A-VoIP, T-Enhancement, O-Frequent, X-Needs-Product
