### ISSUE TITLE
In a 1:1 desktop voice or video call, muting the audio triggers an Android notification. 

### ISSUE THREAD

**Issue by dutchalthoff** [vector-im/element-android#4804] opened 2021-12-22 19:57 UTC
### Steps to reproduce

1. Have both the desktop and Android Element clients signed in to the same account. 
2. Start a 1:1 (voice or video) call on the desktop client.
3. Mute the audio in the desktop client.
4. Check the Android phone for notifications. 

When I asked the #element-android:matrix.org community about this, the response was, "it's always been like that," so it seems like I'm not the only affected user.

#### What did you expect?
I expect no notifications for this event.
Repeatedly muting to silence background/keyboard noise is common in an audio/video desktop call.

#### What happened instead?
Both parties in the call get an Android notification every time someone mutes a 1:1 desktop call.

### Your phone model

Pixel 4a 5G

### Operating system version

Andriod 12

### Application version and app store

1.3.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-12-22 20:11
Duplicate of https://github.com/vector-im/element-web/issues/7941

**Comment by ouchadam** [comment] 2021-12-24 09:44
how strange... this happens for me when calling with `android -> web` clients but not `android -> android`, a blank message appears to come through for each _mute_

| | |
| --- | --- |
|![Screenshot_20211224_094234](https://user-images.githubusercontent.com/1848238/147341433-c59ab1d1-b126-45f4-bd52-f9d4c4220f53.png)|![Screenshot_20211224_094246](https://user-images.githubusercontent.com/1848238/147341431-3d5b8d0a-2130-4b14-9614-1d28bb67720d.png)

**Comment by SimonBrandner** [comment] 2021-12-24 09:57
> how strange... this happens for me when calling with `android -> web` clients but not `android -> android`, a blank message appears to come through for each _mute_

Yes, this is caused by the combination of https://github.com/matrix-org/matrix-doc/pull/3291 and https://github.com/vector-im/element-web/issues/7941

**Comment by ouchadam** [comment] 2021-12-24 10:50
on the client side we're incorrectly assuming all encrypted event types are messages, which causes this ` type=org.matrix.call.sdp_stream_metadata_changed` to be rendered as a notification [code ref](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt#L73)

**Comment by bmarty** [comment] 2021-12-30 10:31
Fixed in 1.3.13

**Closed** 2021-12-30 10:31 UTC
Labels: T-Defect, A-Notifications, A-VoIP, S-Tolerable, O-Frequent
