### ISSUE TITLE
Notifications not being cleared even though they were read

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#3397] opened 2021-05-23 06:30 UTC
#### Describe the bug
I have two Android devices, I am getting notifications on both but one of them does not clear some notifications after being read on the other

#### To Reproduce
Not sure, but it's definitely not easy, I do have logs though - I sent them.

#### Expected behavior
The notifications should be cleared since they were clearly read

#### Screenshots
here's a screen cap:
https://photos.app.goo.gl/SKVPero24vP2uqjH9

#### Smartphone (please complete the following information):
 - Device: Samsung Galaxy A51
 - OS: One UI version 3.1, Android 11

#### Additional context
 - 1.1.7 Google play beta tester
 - Homeserver: chagai.website

**Comment by bmarty** [comment] 2021-05-26 12:24
Duplicate of #3347

**Closed by bmarty** 2021-05-26 12:24 UTC
Labels: feature:notification

**Comment by chagai95** [comment] 2021-05-26 18:05
I don't think it's the same, it does not always happen, just sometimes. This seems different than the other ticket. @bmarty
