### ISSUE TITLE
Infinite sending loop blocks me from sending messages

### ISSUE THREAD

**Issue by faaaaabi** [vector-im/element-android#2037] opened 2020-09-01 07:45 UTC
**Describe the bug**
I send a very large message >> 4000 characters to a group. Now element Android tries to send this message but can't succeed. This blocks me from sending messages to the group as i can't cancel the sending process

A similar behavior was also mentioned in #1938

**To Reproduce**
1. Go to a group and send a very large message >> 4000 characters. I copied the whole content of a website
2. See Element Android endlessly trying to send the message and see you to not be able to send a message to the group ever again

**Expected behavior**
I would appreciate that Element Android informs me about the message to be too big, as Element Desktop/Web does. And also be able to cancel the sending process, as Element Desktop/Web does

**Screenshots**
![Screenshot_20200901-094757](https://user-images.githubusercontent.com/12394037/91823022-e7d45f00-ec38-11ea-8db8-fa3452b8245b.jpg)

**Smartphone (please complete the following information):**
 - Device: One+ 8 pro
 - OS: Andorid 10

**Additional context**
 - App version and store: 1.0.5 Goole Playstore
 - Homeserver: private homeserver synapse:v1.17.0-py3

**Comment by BillCarsonFr** [comment] 2020-09-07 12:56
Duplicate of https://github.com/vector-im/element-android/issues/1397

**Closed by BillCarsonFr** 2020-09-07 12:56 UTC
