### ISSUE TITLE
Give us one tab for all chat like telegram

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-android#3645] opened 2021-07-07 14:21 UTC
I like all chat in one tab or page. As like telegram. I like to see the option to marge direct chat and room together in one tab.
There have a option for unread massage we can spare it or marge it like wise give a option to marge direct chat and room together.

Thanks

**Comment by HarHarLinks** [comment] 2021-07-07 18:10
If I understand you correctly, https://schildi.chat/android/ does what you want.

**Comment by aniseeo** [comment] 2021-07-08 11:37
I know that but schildichat have some bug.

**Comment by kojid0** [comment] 2021-07-08 15:21
This is a duplicate of #650 
Please upvote that issue in order to give it more attention

**Comment by kojid0** [comment] 2021-09-14 08:04
This is a duplicate of #650 which has a lot more upvotes. This issue can be closed.
Also @BillCarsonFr seems to work on tabs currently.

**Comment by bmarty** [comment] 2021-09-14 09:30
Closed in favor of #650

**Closed by bmarty** 2021-09-14 09:30 UTC
Labels: T-Enhancement
