### ISSUE TITLE
Forceful conversion to numbered lists in messages causes messages to change in meaning

### ISSUE THREAD

**Issue by Avamander** [vector-im/element-android#4777] opened 2021-12-20 14:33 UTC
### Steps to reproduce

1. Someone asks me a question:
```
We have three choices here:
1. Pizza with pineapple
2. Sushi
3. Ramen

What do you want to eat?
```
2. I answer: `2. sounds good`
3. I'm brought pizza with pineapple because Element Android changed my `2.` to `1.` due to its internal conversion to numbered list (with a single item)

This is **incredibly** awful.

#### What did you expect?
That my message is displayed how it was sent.

#### What happened instead?
The meaning of my message was changed.

### Operating system version

Android 10

### Application version and app store

1.3.9

### Homeserver

matrix.org

**Comment by ouchadam** [comment] 2021-12-21 13:43
this looks like a missing feature with the markdown/html library we use, have raised an issue https://github.com/noties/Markwon/issues/381

**Comment by notramo** [comment] 2021-12-25 12:40
This is standard Markdown feature (automatically numbering ordered list).
Maybe disable ordered lists in Element?

**Comment by basxto** [comment] 2022-01-26 13:34
Biggest issue is that Element Desktop and Element Android handle this differently, so the answer will look different with different clients. Element Desktop also makes it into a list, but it does not do automatical numbering.

List decorations are also dropped in the _Direct Messages_, there the answer would be just rendered as `sounds good`

**Comment by HarHarLinks** [comment] 2022-04-05 12:04
it is really horrible when you try to make an appointment and e.g. suggest "4. April" and depending whether the other person(s) use(s) element web, android, or iOS, they see "1. April". Then suddenly on 1. April you get a call why you're late.

**Comment by daniellekirkwood** [comment] 2022-06-14 08:52
Have triaged on the WTFs board, will remove myself now 👍

**Comment by Seil0** [comment] 2022-07-01 16:32
How is this only a minor issue? This makes element unusable on Android.

**Comment by notramo** [comment] 2022-07-05 12:26
Because if sponsor reports issue, then it's a serious issue despite if it doesn't even affects the UX (or very minimally - see confetti animation or typing indicator).
If somebody other reports it, who doesn't pay, then it's a minor issue, despite it can be so serious that users migrate back to proprietary chat platforms. See the #2504 call glare bug, which repeatedly makes users migrate back to Facebook™ Messenger™, but the Element Android don't give a s*** for since 2 years, despite it's probably 30 lines of code and probably can be fixed in 20 minute by somebody who is familiar with the codebase (I unfortunately don't know Kotlin, and I'm not familiar with Android development).
So don't expect a fix for this bug either.
Use a client that's developed by volunteers, not a company (Syphon and FluffyChat on mobile, and Cinny on desktop). They probably consider these kind of bugs more important.

**Comment by ouchadam** [comment] 2022-07-05 12:41
to help clear up the labelling, this issue was originally marked as minor because "a suitable workaround exists", which in our case is disabling the markdown preference and the markdown setting is not enabled by default.

however... it seems this is not actually the case and even without the markdown toggle disabled the list syntax is being unexpectedly processed, will upgrade the severity

**Comment by ouchadam** [comment] 2022-07-08 08:13
Fixed in v1.4.28

**Closed by ouchadam** 2022-07-08 08:13 UTC
Labels: T-Defect, A-Markdown, A-Timeline, S-Major, O-Occasional, Z-WTF

**Comment by Avamander** [comment] 2022-07-08 08:48
@ouchadam 

I think that fix would still change the meaning of messages in some scenarios, especially if the behaviour is not unified between platforms. 

For example:

```
What were the deadlines for submission
```
```
Let me check my calendar
```
```
4. August
17. August
```

Would turn the last message into:
```
4. August
5. August
```

**Comment by ouchadam** [comment] 2022-07-08 09:13
unfortunately there's no avoiding the number change when markdown is enabled and the list syntax is used, I can confirm web and android are in sync at least!


Sending the following messages...

```
5. five
10. ten
```

```
/plain
5. five
10. ten
```

| WEB | ANDROID | 
| --- | --- |
|![2022-07-08T10:09:34,188827306+01:00](https://user-images.githubusercontent.com/1848238/177959426-7b2b131d-68b6-4bd7-bac8-1d96f64650af.png)|![2022-07-08T10:10:51,736325070+01:00](https://user-images.githubusercontent.com/1848238/177959458-f9d32ef5-ec15-443c-9e29-048723642ee2.png)
