### ISSUE TITLE
RiotX asks for verification every time when open

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#1362] opened 2020-05-13 09:24 UTC
RiotX v.0.19
Synapse - 1.12.4

Every time when I open RiotX it asks me to verify the session. But this is the only session. I have no other devices with this account. And when I skip the verification and reopen the app again, it asks again to verify.
![Screenshot_2020-05-13-11-41-17_im vector riotx debug](https://user-images.githubusercontent.com/30805725/81795186-84e97b80-9514-11ea-9293-fe4a0472c9a3.jpg)

**Comment by BillCarsonFr** [comment] 2020-05-19 11:59
Did you setup cross-signing with an old session (logged out now)

**Comment by bahur142** [comment] 2020-05-19 16:33
Yes, I did, but logged out. With the prev session it asks me to setup another password (different from login name). But I did not remember it. However I don't want my old messages. I want just to login on another device and continue from now on.

Is this expected behaviour?

**Comment by MadLittleMods** [comment] 2022-04-21 05:38
Related to https://github.com/vector-im/element-android/issues/3571

**Comment by kittykat** [comment] 2022-08-31 12:17
Duplicate of #4318

Thank you for reporting the issue, closing in favour of the newer one

**Closed** 2022-08-31 12:18 UTC
Labels: A-E2EE-Cross-Signing
