### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by brumasribera** [vector-im/element-android#7395] opened 2022-10-18 11:25 UTC
#### What would you like to do?
To be able to switch between multiple Matrix account on the app

#### Why would you like to do it?
So that I can use both the work account together with my personal one.
I would therefore be able to get an Element Home subscription and get my whole family in.

#### How would you like to achieve it?
Probably like Google does on all his apps, sliding up or down on the profile picture plus inside the menu.

### Have you considered any alternatives?

Duplication the app, but it doesn't work.

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment] 2022-10-18 13:38
Duplicate of #26 

Please file new cross-platform feature requests under [Discussions in element-meta](https://github.com/vector-im/element-meta/discussions/categories/ideas?discussions_q=multiple+account+category%3AIdeas)

**Closed by kittykat** 2022-10-18 13:38 UTC
Labels: T-Enhancement
