### ISSUE TITLE
Push notifications received late

### ISSUE THREAD

**Issue by RealTheSunCat** [vector-im/element-android#4393] opened 2021-11-02 11:32 UTC
### Steps to reproduce

1. Receive a message from someone
2. Wait for a few minutes
3. Maybe receive a notification, or not at all

#### What did you expect?
I expect to receive notificatons for messages on the Android app, just like I do on the desktop app.

#### What happened instead?
I rarely receive notifications on time, they are usually delayed by a few minutes or I don't receive them at all.
On a friend's device, they don't receive notifications at all until they open the app. Battery optimization is not set to "Restricted"

### Your phone model

Google Pixel 3a

### Operating system version

Android 12.0

### Application version and app store

Element version 1.3.3 [30103032]; olm version 3.2.4 from Play Store

### Homeserver

allpurposem.at

### Will you send logs?

No

**Comment by Penguin-Guru** [comment] 2021-11-14 02:15
I'm having the same issue on Graphene. O.S. version is also 12. I almost never get notifications, but one of the few I did get was on my phone when I woke up so they may just be very delayed. Darkmaster helped me trouble-shoot in the Element Android room but in the end we couldn't figure it out. The notification bubbles on rooms in the Element app do appear when the app is opened so that much is working.

**System settings:**

- Apps -> Element -> Battery -> "Manage battery usage" is set to "Unrestricted".

- "Battery saver" is disabled (system wide).

- Developer settings should all be default. "Background check" does not list Element. Background process limit is standard. Element is listed as "Exempted" in "Standby apps". "Don't keep activities" is disabled.

- I have not installed or otherwise used any backup/restore apps.

- Typing that *#*#4636#*#* into my dialer and watching the usage statistics confirms that Element did not run for at least two 
minutes after I closed it, which I assume it should with 60 second polling set (see below).

**In the app:**

- Notifications enabled for account and session.

- Default notifications checked for direct messages and encrypted direct messages, then also groups and encrypted groups for testing.

- Both noisy and silent notification settings should be default.

- Background sync mode is real-time with 60 second delay and 6 second timeout.

- Start on boot is enabled and I did try restarting at two points.

- Troubleshoot notifications seems to work fine.

- Legacy init sync did not help.

**Comment by ouchadam** [comment] 2021-11-16 11:37
for some context, whilst the app is open and in the foreground it continuously checks for new messages and they'll appear as notifications, which means it's possible to receive messages without push working correctly

-----

@Penguin-Guru it sounds like you're encountering the fdroid background sync issue https://github.com/vector-im/element-android/issues/4298 which will hopefully be fixed by 1.3.7

-----

@RealTheSunCat could I ask for some extra information to help debug this?


The first thing to check is if the network pushes from [Sygnal](https://github.com/matrix-org/sygnal) + Google Play services are coming through consistently, this can be checked by  

- Enabling developer mode and `show debug info on screen` and check if the push counter increments (top right) at a reasonable rate, for me it usually takes between 1 - 5 seconds for the push count to increment when receiving a message

| SETTINGS | ROOM LIST |
| --- | --- |
![Screenshot_20211116_104038](https://user-images.githubusercontent.com/1848238/141970696-b57a0079-a961-499d-8f0f-5bdf9b2efe1d.png)|![Screenshot_20211116_104051](https://user-images.githubusercontent.com/1848238/141970694-8a257f84-39d0-48fb-bde2-fa7b3674f7cf.png)

- If the count doesn't increment or increments but there's no notification, try going to the room/DM -> settings -> notifications and switching `notify me for` to `none` and back to `all messages`. This will override the cross client push rules, if this fixes the issue it suggests that we need to revisit this area

- if the count goes up and works fine whilst the app is in the foreground, what happens when receiving a message whilst the app is in the background? (but the device is still active), when relaunching the app has the push counter incremented?
  - minimising the app (pressing home) 
  - swiping the app away from the recents menu 
  - force stopping via the application settings

**Comment by ouchadam** [comment] 2021-12-01 11:26
closing due to inactivity and being unable to reproduce locally

**Closed by ouchadam** 2021-12-01 11:26 UTC
Labels: T-Defect, A-Notifications, S-Major, O-Uncommon, X-Needs-Info

**Comment by Penguin-Guru** [comment] 2021-12-01 11:50
My issue (presumed different) was indeed resolved when the persistent notification was recently added. The notifications aren't visible until I unlock my phone and pull down the task bar to check for them, but I think this is due to encrypted rooms not supporting noisy notifications or something like that. There is a statement about it on the room level notification configuration page.

**Comment by ouchadam** [comment] 2021-12-01 12:29
@Penguin-Guru I don't believe this is set within the app but instead by the system, it's possible to change the behaviour via the system app info then selection notifications and then the noisy/silent channels

The UI may look different as these screenshots come from a Android 10 device running MIUI

| CHANNEL SETTINGS | OPTIONS | RESULT |
| --- | --- | --- |
|![Screenshot_20211201_122140](https://user-images.githubusercontent.com/1848238/144234243-54c42d20-cfcb-4fed-bf21-538dd06c8172.png)|![Screenshot_20211201_122738](https://user-images.githubusercontent.com/1848238/144234387-50c44ac6-1d94-47c8-9b36-399a89ce7b53.png)|![Screenshot_20211201_122436](https://user-images.githubusercontent.com/1848238/144234234-0f70cfa5-be2b-4ce1-85e1-0025ce1f2ff5.png)

**Comment by Penguin-Guru** [comment] 2021-12-01 14:17
@ouchadam I see system settings to configure notifications for Element, but options like "Pop on screen" are only available for noisy notifications.

In Element, after opening a room conversation, then settings for that room, then "Notifications", there is a message at the bottom of the screen that says "Please note that mentions & keyword notifications are not available in encrypted rooms on mobile." I'm not sure why this is the case but hopefully support will be added eventually. It really confused me at first because the message does not appear on the default (i.e. not room-specific) notifications settings page. My understanding is that mentions (including replies) and keywords are considered noisy and all other event notifications are silent. Hopefully they will be configurable some day.
