### ISSUE TITLE
UTDs between 2 new accounts created on Element-Android

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#3649] opened 2021-07-08 08:04 UTC
#### Describe the bug
2 new accounts have been created on Element-Android
Each account has only one session (android)
The 2 accounts joined 2 group chats,
The 2 accounts verified each other
 In these 2 rooms they are unable to decrypt each other

Note a third account have been invited in one of this room. When this third account send a message from his iOS session, everyone can decrypt it.
The third account can decrypt message from android sessions too

UTDs are systematic between the 2 android sessions only

Rage shakes from the 2 android devices have been sent

**Comment by crashbandicode** [comment] 2021-07-08 20:37
If the two android accounts message each other on Fluffy Chat (still with only one session) are they able to read them?

**Comment by akallabeth** [comment] 2021-07-13 12:27
Got a similar issue in recent days.
1. Got some new contacts to use matrix, they created an account and we created a room to write to each other.
1. After a day the other end did signal that the messages could not be decrypted.
* Both accounts on matrix.org, one already quite old.
* Creating a new room to talk did fix the issue (but it is an annoying first experience :/)

**Comment by crashbandicode** [comment] 2021-07-13 13:33
Try the fdroid version 1.1.9 (not from google play or the aurora store) and see if it fixes the issue. We ran into this as well and installing that version from f-droid seems to have helped.

**Comment by BillCarsonFr** [comment] 2021-07-22 14:27
caused by #3725 closing as duplicate thanks for the report

**Closed by BillCarsonFr** 2021-07-22 14:27 UTC
