### ISSUE TITLE
groups don't update

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-android#836] opened 2020-01-13 17:28 UTC
If you join a new group via riot-web it doesn't show up in riot x. If you clear cache none show up anymore

**Comment by bmarty** [comment] 2020-01-13 20:56
FTR, after a clear cache it works well on my account.

**Comment by Sorunome** [comment] 2020-01-13 20:57
After quite some waiting they appeared (only noticed just now).....however only the old ones, not the new ones joined

**Comment by heyakyra** [comment] 2020-08-24 23:25
Should this be marked as a duplicate of  #479 for simplicity?

**Comment by bmarty** [comment] 2021-03-23 20:21
Group will be replaced by spaces very soon

**Closed by bmarty** 2021-03-23 20:21 UTC
Labels: feature:group
