### ISSUE TITLE
The ringtone plays through the "speaker mode" system instead of the "default calling" system when calling someone.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-android#4781] opened 2021-12-20 23:24 UTC
### Steps to reproduce

1. Call an individual
2. Put the phone up to your head, assuming it will behave like normal.
3. Experience hearing loss from the phone blaring at an unadjustable volume on speaker mode.
4. The call itself starts and it is no longer speaker mode, without any user interaction.

#### What did you expect?
I expected that the phone would behave like normal and not play at maximum "speaker mode" volume without me specifying for that to happen
#### What happened instead?
The app likely caused me hearing damage, this has happened multiple times because it is the practical behavior of every calling app I've ever used. Kind of annoyed because both the notification noise on the desktop app & this have been physically damaging to me & others and they don't seem to be getting worked on. (see https://github.com/vector-im/element-web/issues/5891#issuecomment-965898674)

### Your phone model

Pixel 4a 5G

### Operating system version

Android 11

### Application version and app store

Element version 1.3.9 Olm version 3.2.4

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by ouchadam** [comment] 2021-12-21 11:04
this sounds like an awful bug, to confirm the issue is 

1. start a voice call
2. the app incorrectly defaults to the speaker
 
---

for extra context the outgoing ringing volume is currently controlled by the media volume and different oems/skins/android OS's handle the volume controls slightly differently

| Android 10 (MIUI) | Android 11 (One UI) | Android 11 (One UI) expanded |
| --- | --- | --- |
![miui-in-call-volume](https://user-images.githubusercontent.com/1848238/146917966-703e2741-934c-4fe7-8a79-afed0785d7ac.png)|![b4a046a5-440b-4800-a312-3d9bc090436a](https://user-images.githubusercontent.com/1848238/146917985-c9abf391-02c1-4bc0-9d49-f266ae8cbc52.jpeg)|![1bf8e823-c5e4-4626-af32-81003bbb2797](https://user-images.githubusercontent.com/1848238/146918914-8b99dc1e-a1d3-4a22-9cbe-ffe5dfdd0ceb.jpeg)

**Comment by AverytheFurry** [comment] 2021-12-21 18:36
> this sounds like an awful bug, to confirm the issue is 
> 
> 1. start a voice call
> 2. the app incorrectly defaults to the speaker
>  
> ---
> 
> for extra context the outgoing ringing volume is currently controlled by the media volume and different oems/skins/android OS's handle the volume controls slightly differently
> 
> | Android 10 (MIUI) | Android 11 (One UI) | Android 11 (One UI) expanded |
> | --- | --- | --- |
> ![miui-in-call-volume](https://user-images.githubusercontent.com/1848238/146917966-703e2741-934c-4fe7-8a79-afed0785d7ac.png)|![b4a046a5-440b-4800-a312-3d9bc090436a](https://user-images.githubusercontent.com/1848238/146917985-c9abf391-02c1-4bc0-9d49-f266ae8cbc52.jpeg)|![1bf8e823-c5e4-4626-af32-81003bbb2797](https://user-images.githubusercontent.com/1848238/146918914-8b99dc1e-a1d3-4a22-9cbe-ffe5dfdd0ceb.jpeg)
> 

Yes, except the ringtone is the only part which starts in speaker mode. It then reverts back to normal after. Im running lineageos 18.1 btw. Ive attached an image of what my sound system looks like.![Screenshot_20211221-103447_GitHub.png](https://user-images.githubusercontent.com/47131867/146981195-ef47a471-3a66-4059-be07-651ebd05206a.png)

**Comment by bmarty** [comment] 2022-01-05 21:05
Should be fixed in 1.3.13 🤞

**Closed** 2022-01-05 21:05 UTC
Labels: T-Defect, A-VoIP, S-Major, O-Uncommon

**Comment by AverytheFurry** [comment] 2022-01-09 21:20
> Should be fixed in 1.3.13 🤞 

Nope! Still happening.

**Comment by ouchadam** [comment] 2022-01-10 08:46
to double check, which build was used? (we haven't released 1.3.13 yet)

**Comment by AverytheFurry** [comment] 2022-01-10 08:48
> to double check, which build was used? (we haven't released 1.3.13 yet)

Oh im not using the updated version then, sorry!

**Comment by AnisTaluqdar** [comment] 2022-01-12 05:23
@bmarty I can confirm. still, the same problem is occurring in 1.3.13.

**Comment by ouchadam** [comment] 2022-01-12 09:20
@AnisTaluqdar are you also running Lineage OS?

**Comment by AnisTaluqdar** [comment] 2022-01-12 09:25
> @AnisTaluqdar are you also running Lineage OS?

no. Android 11 with Gplay

**Comment by ouchadam** [comment] 2022-01-12 09:29
:+1: 

and to confirm your issue, when starting an audio call, the speaker is used instead of ear piece (using the 1.3.13 apk or beta from the play store)

**Comment by AnisTaluqdar** [comment] 2022-01-12 09:31
In audio call It use ear piece but the sound is related to media volume. And sorry the android version is 10 not 11

**Comment by AnisTaluqdar** [comment] 2022-01-12 09:40
Other messenger use always call volume whether it is in speaker or ear piece but element always use media volume in my phone even in 1.3.13

**Comment by ouchadam** [comment] 2022-01-12 09:56
ahhh! that sounds like #3391 which hasn't been addressed yet (outgoing call ringtones using the media volume)

this issue #4781 is for the device speaker incorrectly being used for the ringing when starting an audio call
