### ISSUE TITLE
when in voip call, second incoming call keeps ringing, despite of rejecting call

### ISSUE THREAD

**Issue by atuctuc** [vector-im/element-android#7772] opened 2022-12-12 16:08 UTC
when i am in a call and a second call comes in, when i reject the incoming call, the ring continues (in the headphone). also when i pick up the second call on my second android, it's the same. i have to cancel the call to stop the ring signal.

**Comment by kittykat** [comment] 2023-02-15 14:50
Duplicate of #3638

**Comment by mnaturel** [comment] 2023-02-20 08:38
Thanks @atuctuc for raising this issue, I am closing this one in favor of the existing one: #3638

**Closed by mnaturel** 2023-02-20 08:38 UTC
