### ISSUE TITLE
Rooms sorted randomly when sharing with RiotX

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-android#901] opened 2020-01-26 12:04 UTC
Hi!
When I share something to RiotX, the list of rooms displayed seems to be displayed in a random order.

Steps to reproduce:
* Have more than 3 dozens of rooms (including ones linked with IRC), including very old ones (I'm a long time user), some tagged as favorites, and with various notification settings
* Don't read all the rooms, just one or two private rooms that have unread messages (remember these rooms)
* Go to YouTube
* Select a video and share it with RiotX
* See the order of the rooms in the list

## What happens?

The list of rooms from which to choose to share is in a non deterministic order. The room I just read is at the ~30th position from the top, with lots and lots of rooms in between, including old rooms ones without any message since months, as well as ones still active.

I really wasn't able to detect a pattern here.

## What did I expect?

The rooms to be sorted by "most recently read" order and this seeing my recently read rooms at the very top.

## Information

RiotX: 0.13.0 [40013002] (G-b1621)
SDK: 0.0.1 (f471d9cf)
OLM: 3.1.2

**Comment by tulir** [comment] 2020-01-26 12:24
Duplicate of #771, already fixed on develop

**Closed** 2021-03-17 15:36 UTC
