### ISSUE TITLE
I want to add the "Use Proxy" feature to the settings of the software

### ISSUE THREAD

**Issue by Fhokud** [vector-im/element-android#6922] opened 2022-08-24 04:18 UTC
### Your use case

I want to add the "Use Proxy" feature to the settings of the software.
This feature is important to help users access the network easily and quickly through a proxy.
Not only Android, but other clients should also add this feature.

The proxy agreement is socks or http or other

### Have you considered any alternatives?

Yes, I consider using vPNs and system proxies, but both handle traffic from other software

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2022-09-05 08:24
Duplicate of #488.

**Closed by jmartinesp** 2022-09-05 08:24 UTC
Labels: T-Enhancement, S-Minor, O-Uncommon
