### ISSUE TITLE
Is there a way to FOLLOW friends rooms channels and see what channels they participate in etc?

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-android#6057] opened 2022-05-14 22:13 UTC
#### What would you like to do?
Would like those I connect with in Direct Messages and possibly in some channels to be allowed (based on my settings for those rooms to share or not?) to see what rooms/channels I participate in and to be able to likewise see/follow channels/rooms my friends are on...
#### Why would you like to do it?
Just because.

#### How would you like to achieve it?
Likely by hoping some developer sees this and wants it too?

**Comment by bbhtt** [comment] 2022-05-16 03:53
This is https://github.com/vector-im/element-android/issues/4573 I think. There is a spec proposal for this feature, tracked as MSC2666.

**Comment by turt2live** [comment] 2022-05-27 05:26
Closing as a duplicate of https://github.com/vector-im/element-android/issues/4573

**Closed by turt2live** 2022-05-27 05:26 UTC
Labels: T-Enhancement
