### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by parsifallo** [vector-im/element-android#5028] opened 2022-01-21 22:12 UTC
### Steps to reproduce

1. Upgrade to current Element version via Fdroid Store
2. Let someone write you a message

#### What did you expect?
Getting notifications
#### What happened instead?
Won't receive push/background sync notifications. Starting sync only on application start. Same happend with my wife's Element installation (Huawei P40pro Stock, Fdroid)

Don't know if this is connected: I tried to install the play store version, push ist not working either. Stops at "Test push - The application ist waiting for the PUSH". Play Services onstalled, other push notifications work for me on Graphene

### Your phone model

Pixel 5

### Operating system version

Android 12 GrapheneOS

### Homeserver

private

### Will you send logs?

Yes

**Comment by lindhe** [comment] 2022-01-21 22:49
Me too!

I updated via Google Play Store to version 1.3.15 on a Samsung Galaxy S21. 

Related to #5016?

**Comment by Karamelmar** [comment] 2022-01-22 03:01
+1
both on the most recent fdroid and google play version.

**Comment by ozoned** [comment] 2022-01-22 16:32
+1
Wife's Motorola Moto E

I went into the Element settings and tested the notifications and everything does function.  

Also, interestingly enough, it seems like mobile to mobile messages via Element, she gets a notification.  But desktop to her mobile, she doesn't.

**Comment by kavemang** [comment] 2022-01-22 19:45
+1 F-droid on samsung

**Comment by Buntbart** [comment] 2022-01-23 11:21
+1
Samsung Galaxy S5 running  LineageOS 18.1 (Android 11), no Google Play Services installed. Since last update Element (F-Droid-Version) seems to hibernate when in background. Battery Optimization is switched off for Element. Messages are fetched when I actively open Element and only *then* there are also notifications.

**Comment by Danacus** [comment] 2022-01-23 20:46
+1
LineageOS for microG. Notifications are not working and new messages aren't being fetched either.

**Comment by mjmccans** [comment] 2022-01-24 01:18
+1
Both my wife and I have Pixel 5s and have the same issue. Testing notifications works, but we do not get notifications when we send each other messages.

**Comment by ouchadam** [comment] 2022-01-24 12:27
I'm going to close this issue in favour of dedicated variant issues as google play and fdroid have very different notification/syncing systems

for fdroid users, there was a regression introduced in 1.3.14 which broke battery optimised background syncing https://github.com/vector-im/element-android/issues/5003 switching to real time is the current workaround, if this doesn't fix your issue please comment in linked issue and I'll reopen

for google play, I've raised a dedicated issue https://github.com/vector-im/element-android/issues/5038 it would be great if people who are affected are able to provide their homeserver versions and whether they're receiving raw pushes

**Closed by ouchadam** 2022-01-24 12:27 UTC
Labels: T-Defect
