### ISSUE TITLE
New App Layout | PagedList is buggy (long placeholders, jumpt to top)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#7079] opened 2022-09-08 09:21 UTC
When using the new layout (nighlty) I have several problems with the room list:
- Placeholders appearing fast and stay quite long (can be forever). It's not happening in production app
- When placehodlers are replaced the list sometimes jump to top

**Comment by daniellekirkwood** [comment] 2022-09-12 11:27
I this a duplicate of this: https://github.com/vector-im/element-android/issues/7028

**Comment by fedrunov** [comment] 2022-09-12 14:51
> I this a duplicate of this: #7028

No, it's not, it looks more like it's another symptom of slow list loading from this https://github.com/vector-im/element-android/issues/7030

**Closed** 2022-09-19 13:22 UTC
Labels: S-Major, Z-AppLayout
