### ISSUE TITLE
Add support for bubbles chats

### ISSUE THREAD

**Issue by thanasistrisp** [vector-im/element-android#6117] opened 2022-05-21 23:12 UTC
#### What would you like to do?
Show conservation as bubbles, like messenger, google messages, signal, etc. This is available in Android 11+
#### Why would you like to do it?
In group messaging apps it is critical to have it even for selected conservations if not all.
#### How would you like to achieve it?
[Bubbles | Android Developers](https://developer.android.com/guide/topics/ui/bubbles)

**Comment by AlexAltea** [comment] 2022-06-03 17:19
Duplicate of https://github.com/vector-im/element-android/issues/979

> Bubbles are now supported in Element app (since v1.4.0 (2022-02-09)), please create new dedicated issues for any related problem/enhancement.

Check Settings > Preferences > Show Message bubbles (under *Timeline* category)

**Comment by AlexAltea** [comment] 2022-06-03 17:21
@ouchadam This should be closed.

**Comment by VelocityDesign** [comment] 2022-06-05 04:15
Hi @AlexAltea! I believe that @thanasistrisp meant that having support for the "Bubbles" feature as shown on the Android 11 site, as opposed to a style of displaying messages while in the app.

![Screenshot of a page on the Android website explaining message bubbles](https://user-images.githubusercontent.com/24457862/172034695-02c74ae7-a8ec-4c79-978d-2a751341fdae.png)

I do vaguely remember Element possibly having this feature at some point, but I'm not 100% sure. At some point tomorrow, I'll test to see if the feature is already implemented, unless someone replies with a definite answer.

**Comment by ouchadam** [comment] 2022-06-06 08:29
As far as I'm aware Element doesn't support bubble overlays yet as we need to allow the timeline screen to be expandable, it could be a simple case of adding the new XML tags to opt in :crossed_fingers:  but I haven't tested

**Comment by genofire** [comment] 2022-06-20 16:25
I believe it is duplicated of:
 #1124 which is part of #1722.

If i am correct, please close this issue.

**Comment by VelocityDesign** [comment] 2022-06-21 01:43
> I believe it is duplicated of: #1124 which is part of #1722.
> 
> If i am correct, please close this issue.

Yep! I don't know who to @mention in order to get it closed, but I can confirm.

**Comment by ouchadam** [comment] 2022-06-21 09:24
:+1:  thanks for linking the other issue, let's close this in favour of https://github.com/vector-im/element-android/issues/1124

**Closed by ouchadam** 2022-06-21 09:24 UTC
Labels: A-Notifications, T-Enhancement, X-Needs-Product
