### ISSUE TITLE
Sharing a file from the gallery only works with multiple recipients

### ISSUE THREAD

**Issue by murlock1000** [vector-im/element-android#7535] opened 2022-11-07 17:04 UTC
### Steps to reproduce

1. Open any gallery app, select one or more images to send.
2. Click "Send items" to Element.
3. The element room selection opens.
4. Hold down the room entry to select the room I want to send the image to. (Select only one room).
5. Press the send button.

#### What did you expect?
The image to be sent to the room.
#### What happened instead?
The room chat window opened and the image was not sent.

### Your phone model

Mi 9T

### Operating system version

Android 10 QKQ1.190825.002

### Application version and app store

Element version 1.5.4 [40105042] (G-b12120), Matrix SDK version 1.5.4 (db35f5c7), olm version 3.2.12

### Homeserver

non-public Synapse

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by lsowen** [comment] 2022-11-08 00:41
I'm having the same issue, regardless of the shared item (image, link) or source (gallery, browser).  Version 1.5.4 [40105040] (F-db35f5c7)

**Comment by nicuh** [comment] 2022-11-08 13:00
Same issue for me:

Element version 1.5.4 [40105042] (G-b12120), Matrix SDK version 1.5.4 (https://github.com/vector-im/element-android/commit/db35f5c7f2a33a13217ecc069989df74ab6db375), olm version 3.2.12
Android 10 / Samsung Galaxy A51

**Comment by jmartinesp** [comment] 2022-11-08 16:43
Hi, this is probably a duplicate of #7525. Please install version 1.5.7 once it's published, it should be fixed there. If the issue persists, please re-open this issue and let us know.

**Closed by jmartinesp** 2022-11-08 16:43 UTC
Labels: T-Defect
