### ISSUE TITLE
VoIP timeline tweaks

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-android#2899] opened 2021-02-21 22:11 UTC
**Is your feature request related to a problem? Please describe.**

The 1.1.0 update has just landed in the Play Store and already I'm getting some suggestions from users :P
The following have been mentioned:
- (1) No way to/too difficult to tell when a call has started, ended and how long it lasted (especially the latter)
- (2) The call logs take up too much space in the timeline for the information they display

**Describe the solution you'd like**

- (1) The call log "bubble" could include this information
- (2) Depending on the design of the above, the call log bubble could also be shrunk a little.

**Describe alternatives you've considered**

- (2) Some additional actions could be included in the bubble, like "call again", to justify its size.

**Additional context**

N/A

**Comment by kittykat** [comment] 2021-11-17 16:39
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat if you still experience the issue with v1.3.8 (coming out next week).

**Closed by kittykat** 2021-11-17 16:39 UTC
Labels: A-VoIP, T-Enhancement
