### ISSUE TITLE
unnamed rooms show roomid in space room management screen

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#3647] opened 2021-07-07 18:16 UTC
#### Describe the bug
unnamed rooms show roomid in space room management screen
especially DMs

#### To Reproduce
1. Go to Space -> Manage rooms and spaces

#### Expected behavior
human readable names

#### Smartphone (please complete the following information):
 - Device: [e.g. Samsung S6]
 - OS: Android 10

#### Additional context
 - App version and store 1.1.11
 - Homeserver: [e.g. matrix.org]

**Comment by kittykat** [comment] 2022-01-07 12:01
Duplicate of #3376

**Closed by kittykat** 2022-01-07 12:01 UTC
Labels: A-Spaces
