### ISSUE TITLE
Support MP3, Flac & M4A playback on mobile

### ISSUE THREAD

**Issue by trymeouteh** [vector-im/element-android#2649] opened 2021-01-09 19:56 UTC
Please add support for playing sent MP3, FLAC & M4A files on the Android and iOS clients.

**Comment by kojid0** [comment] 2021-01-09 20:16
Duplicate of #29

**Comment by trymeouteh** [comment] 2021-01-09 20:47
> Duplicate of #29

Not a duplicate, this is about playing any MP3, Flac or M4A file on element mobile. Not just voice messages and not recording voice messages. You can only play MP3, Flac or M4a files on the desktop that are sent to you, this is not possible on mobile.

**Comment by G2G2G2G** [comment] 2021-08-07 12:03
and lossy formats that aren't 30 years old, like opus etc.

**Comment by G2G2G2G** [comment] 2021-08-07 12:05
Looks like this is actually a duplicate of this one: https://github.com/vector-im/element-android/issues/2525

**Comment by kojid0** [comment] 2022-02-01 20:55
Would it be possible to display such files as voice messages?

**Comment by ouchadam** [comment] 2022-02-17 11:08
thanks for raising! lets centralise the issue to #2525 (which has had its priority upgraded to _z-wtf_)

**Closed by ouchadam** 2022-02-17 11:08 UTC
Labels: T-Enhancement
