### ISSUE TITLE
Audio messages

### ISSUE THREAD

**Issue by Gushtera** [vector-im/element-android#2795] opened 2021-02-07 19:46 UTC
Hello guys,
do you plan to implement audio messages?

**Comment by SimonBrandner** [comment] 2021-02-07 19:59
Duplicate of [#29](https://github.com/vector-im/element-android/issues/29)

@Gushtera Yep, I believe this is planned

**Comment by SimonBrandner** [comment] 2021-02-07 19:59
@Gushtera Yep, I believe this is planned

**Comment by bmarty** [comment] 2021-02-08 14:58
Yes, dup of #29, it's coming soon(tm)

**Closed by bmarty** 2021-02-08 14:58 UTC
Labels: type:suggestion
