### ISSUE TITLE
Notification does not take me to the room when another space was last viewed

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3839] opened 2021-08-16 12:10 UTC
#### To Reproduce
For these steps, lets assume that the user has two spaces, Space1 and Space2
1. Go to Space1
2. Lock screen
3. Receive notification from a room in Space2
4. Click on the notification on the lockscreen

I see the list of rooms in Space1

#### Expected behavior
I would expect the app to open with a view of the room where the notification came from in Space2

If I last view Space2 before receiving the notification for Space2, the notification opens the correct room.

#### Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 11

#### Additional context
 - App store, version 1.1.15 [40101152] (G-b2969)
 - Homeserver: matrix.org

**Comment by BillCarsonFr** [comment] 2021-09-17 12:37
I tried to reproduce, and it's opening the room but it's not switching to the space
Can you confirm that clicking on the notification did nothing?

**Comment by kittykat** [comment] 2022-01-07 12:09
Fixed now

**Comment by frakic** [comment] 2022-06-14 13:41
Cannot reproduce. Closing.

**Closed by frakic** 2022-06-14 13:41 UTC
Labels: T-Defect, A-Spaces, Z-Papercuts
