### ISSUE TITLE
Cannot login to any server if matrix.org is not available

### ISSUE THREAD

**Issue by iz4tow** [vector-im/element-android#6910] opened 2022-08-22 15:44 UTC
### Steps to reproduce

1. Logout
2. Block matrix.org
3. Launch the application
4. It says: "No internet connection" (also on Ubuntu)

(I'm experiencing this kind of issue because in this country they are blocking matrix.org but I have my private server)
To bypass the problem I had to use an European VPN, open the app, change the HOMESERVER string, shutdown the VPN and then login) 

So to workaround:

1. Connect to a VPN server in a country that allow matrix.org
2. Launch the application
3. Change homeserver string and accept the certificate
4. Shudown VPN client
5. Login to private homeserver

#### What did you expect?
I'm expecting that the App (on PC, Android,...) is working also when matrix.org is not available.

#### What happened instead?
If I'm logged in no issue, but if I have to do the login and matrix.org domain is blocked the application doesn't work saying "No Internet Connection"
I think the connection error should be after the HOMESERVER setting, so if matrix.org is blocked I can however login to a different HOMESERVER

### Operating system version

Android 12 and Ubuntu 20.04

### Application version and app store

Element 1.4.32 on Android & Element 1.11.3 on Ubuntu

### Homeserver

private homeserver

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment] 2022-08-22 15:47
thanks for raising, going to close a duplicate of https://github.com/vector-im/element-android/issues/6718 

there's a fix on the way, will hopefully make it into tomorrows release candidate

**Closed by ouchadam** 2022-08-22 15:47 UTC
Labels: T-Defect

**Comment by iz4tow** [comment] 2022-08-22 19:16
Ok thanks for the quick reply and I'm sorry for the duplicate issue.
You are doing a great job
