### ISSUE TITLE
Notifications being removed too frequently 

### ISSUE THREAD

**Issue by yeltnar** [vector-im/element-android#7773] opened 2022-12-12 18:09 UTC
### Steps to reproduce

When the Android Activity associated with a conversation is running and send to the background, notifications are sill immediately dismissed. 

Steps to reproduce:
Open conversation
Go to the Home screen. 
Send message (from another device and account) to the same conversation. 

#### What did you expect?
When the app is in the background, no notifications should be hidden

#### What happened instead?
When the conversation Activity is running in the background, all notifications in that conversation are immediately dismissed. 

### Your phone model

Pixel 6

### Operating system version

Android 13, GrapheneOS

### Application version and app store

Element version 1.5.8, 1.5.10, 1.5.11

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by onurays** [comment] 2022-12-13 08:53
Closing since duplicate of #7643.

**Closed by onurays** 2022-12-13 08:53 UTC
Labels: T-Defect, A-Notifications, S-Major, O-Frequent
