### ISSUE TITLE
Rich text editor: missing emoji button

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-android#7637] opened 2022-11-25 07:31 UTC
### Steps to reproduce

1. Enable rich text editor
2. Go to some room
3. No emoji button anymore
![obrazek](https://user-images.githubusercontent.com/15554561/203925346-f4c1fb77-95dd-466a-a90c-94ed0554d42e.png)

#### What did you expect?
Visible emoji button as in previous text editor.
#### What happened instead?
No emoji button visible.

### Your phone model

Samsung Galaxy S20 FE

### Operating system version

Android 12

### Application version and app store

Element: 1.5.8

### Homeserver

self hosted Synapse 1.71.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2022-11-25 11:25
Hi. This is a duplicate of #7460. There's planned work to add some way of inserting emojis in the text besides the keyboard ones, but there are items with more priority. Thanks for reporting.

**Closed by jmartinesp** 2022-11-25 11:25 UTC
Labels: T-Defect
