### ISSUE TITLE
Mic is shown on text message notification during a call

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#4142] opened 2021-10-02 12:21 UTC
### Steps to reproduce

1. Make a voice call
2. Send a message

![image](https://user-images.githubusercontent.com/14617699/135715963-8c845d8b-7e0d-4294-ace7-b543d73df15e.png)

### Operating system version

Android 11

### Application version and app store

The latest beta from GPlay

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment] 2021-11-17 16:35
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat and more info if it's still valid for you

**Closed by kittykat** 2021-11-17 16:35 UTC
Labels: T-Defect, A-Notifications, A-VoIP

**Comment by 532910** [comment] 2021-12-23 22:17
Not fixed, reopen please!

**Comment by 532910** [comment] 2022-01-16 09:18
Not fixed, reopen please!
