### ISSUE TITLE
Samsung keyboard issue

### ISSUE THREAD

**Issue by iz4tow** [vector-im/element-android#7495] opened 2022-10-31 16:50 UTC
### Steps to reproduce

1. Use Samsung keyboard as default input
2. Try to compose a message and press enter (to enter a new line not to send)

1. In some cases I had also issue with login

The workaround in both cases is to set Gboard as default input method 

#### What did you expect?
New line when I push enter on the Samsung keyboard 
#### What happened instead?
Typed message disappeared

### Your phone model

Samsung Galaxy s21

### Operating system version

Android 12

### Application version and app store

Last on playstore

### Homeserver

Private homeserver, last version

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by wurza** [comment] 2022-11-01 20:31
Same here with the AnySoftKeyboard. The issue disappears when switching to the Gboard.

**Comment by jmartinesp** [comment] 2022-11-02 08:40
Thanks for reporting! This seems to be a duplicate of #7357. It has already been fixed and will be available when the next app version is published!

**Closed by jmartinesp** 2022-11-02 08:40 UTC
Labels: T-Defect
