### ISSUE TITLE
Allow all noisy notifications for direct messages - not just upon first received (google play)

### ISSUE THREAD

**Issue by binarydad** [vector-im/element-android#5095] opened 2022-01-28 15:05 UTC
#### What would you like to do?

I see I'm receiving notifications just fine, and none are missing. The issue is, upon receiving my first message, I would get a "noisy" notification. However, if another message comes in, I don't get a noisy notification. I do see that they are being added to the notifications when swiped down, but they are silent. My of my chats are direct 1-on-1.

#### Why would you like to do it?

If I happen to miss that first notification (phone is in pocket, etc), I'm never aware of additional (possibly urgent) messages received. Element for desktop creates a noisy notification for every message, as does FluffyChat. I wish Element Android behaved the same way.

#### How would you like to achieve it?

Allow an option for "noisy notifications for every direct message received".

### Have you considered any alternatives?

Yes, FluffyChat works as I would like, but I do not care for other aspects of the app.

I do not believe this relates to this issue: https://github.com/vector-im/element-android/issues/5038

**Comment by marcusaram** [comment] 2022-01-28 15:17
I think it is related to that issue, because it was working that way. Now it doesn't behave anymore like that.

**Comment by binarydad** [comment] 2022-01-28 15:22
> I think it is related to that issue, because it was working that way. Now it doesn't behave anymore like that.

Ok, I wasn't sure because I do in fact see notifications coming in, they're just not NOISY.

**Comment by ouchadam** [comment] 2022-01-28 15:30
@marcusaram there might be some confusion~ #5038 is about notifications not showing up at all whereas this issue is for allowing notifications from direct messages to notify (make a sound/vibrate) for each new message

the change to only notify (make a sound/vibrate) for the first unread message in a room was introduced in `1.3.4`
 
for reference
https://github.com/vector-im/element-android/issues/4632
https://github.com/vector-im/element-android/issues/4398

**Comment by binarydad** [comment] 2022-01-28 15:37
I understand. I can see how that can be really annoying for rooms, etc, but direct messages are a different beast. What I'm not understanding is there are settings for notifying in group chats only for "Mentions & Keywords", so this should've resolved the noisy-ness in either regard.

This should be an option to toggle. Element is the only messaging app I have/use that only notifies upon the first message received.

**Comment by marcusaram** [comment] 2022-01-28 15:43
@ouchadam Oh ok, then I first ran into that issue and after playing with settings. (enabling and disabling push, debugging etc) I had this behavior. Sorry for the noise :sweat_smile:.

**Comment by ouchadam** [comment] 2022-01-28 15:49
> I understand. I can see how that can be really annoying for rooms, etc, but direct messages are a different beast. What I'm not understanding is there are settings for notifying in group chats only for "Mentions & Keywords", so this should've resolved the noisy-ness in either regard.
> 
> This should be an option to toggle. Element is the only messaging app I have/use that only notifies upon the first message received.

totally agree, part of the original problem stems from the default rules for rooms being to notify for every message and android lacking the ability to enable notifications for mentions (rooms currently have all or nothing)  


>@ouchadam Oh ok, then I first ran into that issue and after playing with settings. (enabling and disabling push, debugging etc) I had this behavior. Sorry for the noise sweat_smile.

no worries! that information is helpful but for the other ticket :smile: the missing notification issue is quite troublesome to reproduce...

**Comment by ouchadam** [comment] 2022-02-17 10:58
I'm going to close this issue and centralise the topic to #4632

**Closed by ouchadam** 2022-02-17 10:58 UTC
Labels: A-Notifications, T-Enhancement, X-Needs-Product
