### ISSUE TITLE
sharing web links out of the browser didn't work.

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-android#7545] opened 2022-11-08 15:27 UTC
### Steps to reproduce

Have this Problem with multiple Browser and Matrix-Accounts
1.  Try to share a website out of a browser
2. Click on Element
3. Click on the desired Room.

#### What did you expect?
The link is postet into the room

#### What happened instead?
I get into the room without posting the link.

### Your phone model

Xiaomi Redmi 4x, Mi 10T, Mi 11 Lite, VFD 1400

### Operating system version

Android 11, 12, 6.0.1

### Application version and app store

1.5.4 Olm 3.2.12 GPlay

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by Mozoloa** [comment] 2022-11-08 20:13
The same thing happens with any object you want to share, images and videos have the same glitch

**Comment by jmartinesp** [comment] 2022-11-09 11:17
Hi, thanks for reporting. This issue is a duplicate of #7400, it has already been fixed and you can update to `v1.5.7` to get rid of the issue.

**Closed by jmartinesp** 2022-11-09 11:17 UTC
Labels: T-Defect
