### ISSUE TITLE
Cannot dismiss "New login. as this you?" without verifying the login

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-android#4561] opened 2021-11-25 00:10 UTC
### Steps to reproduce

I have historical unverified logins that I can't verify because I'm not logged into them anymore.

![Screenshot_20211125-110333_Element](https://user-images.githubusercontent.com/57377/143327967-a1797db4-4866-415f-bdef-4d5021510d13.jpg)

#### What did you expect?

To be able to acknowledge the warning and get on with life.

#### What happened instead?

* There is no option to say "I know, but I'd like to ignore it". There is only the option to say "this wasn't me" which isn't the case.
* When I say "this wasn't me" and then "skip", it doesn't skip - the warning is still there with no change.

![Screenshot_20211125-110413_Element-1](https://user-images.githubusercontent.com/57377/143327801-bd5711ed-7d23-41da-8cf4-ef4f2b5c3578.jpg)

I logged out all of my sessions via Element Web to clear this, but that didn't make the warning go away on Android until about 5 minutes later 🤷 

### Your phone model

Galaxy S21

### Operating system version

Android 11

### Application version and app store

1.3.7 [40103072] (G-b4267)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by novocaine** [comment] 2021-11-25 00:11
https://github.com/matrix-org/element-android-rageshakes/issues/28436

**Comment by ouchadam** [comment] 2021-11-26 09:22
thanks for raising, going to close as a dupe of https://github.com/vector-im/element-android/issues/4025

**Closed by ouchadam** 2021-11-26 09:22 UTC
Labels: T-Defect
