### ISSUE TITLE
Optional message bubbles

### ISSUE THREAD

**Issue by iiitomo** [vector-im/element-android#2388] opened 2020-11-14 00:18 UTC
This feature has been nicely implemented by SchildiChat (a fork of element-android). https://github.com/SpiritCroc/SchildiChat-android

Would be nice to add it to Element.

**Comment by witchent** [comment] 2020-11-16 13:16
Duplicate of https://github.com/vector-im/element-android/issues/1805 and https://github.com/vector-im/element-android/issues/979
(Maybe the newer one of them should be closed as well)

**Comment by kittykat** [comment] 2021-09-03 14:25
Thank you for requesting this feature. I am going to close this issue as this is a duplicate of #979

**Closed by kittykat** 2021-09-03 14:25 UTC
Labels: T-Enhancement
