### ISSUE TITLE
SoftLogout UX is broken if the homeserver supports both password and SSO

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5311] opened 2022-02-22 21:08 UTC
SoftLogout UX is broken if the homeserver supports both password and SSO like for instance matrix.org.

Mainly because this block is empty:
```kotlin
is LoginMode.SsoAndPassword -> {
}
```
https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutController.kt#L125

In this case, the app should display the password form, if the user has created the session using a password. If SSO was used, a message like "Please clear data and log in again to your account" can be displayed.

The fact that the user has created the session using a password is not stored. This info can be stored in the `SessionParamsEntity` as a nullable boolean. A database migration will be required.

- boolean is null (we do not have the info) -> Display the password form and a message like "If you have signed in using an account from another provider, please clear data and log in again to your account"
- boolean is true or false: see above

Simulating a soft logout can be done by adding this line: 

```kotlin
globalErrorReceiver.handleGlobalError(GlobalError.InvalidToken(softLogout = true))
```

[here](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt#L153) (for instance)

Critical because the user cannot recover their session in case of soft logout.

**Comment by langleyd** [comment] 2022-02-22 21:14
Duplicate of https://github.com/vector-im/element-android/issues/5192, whichever one you want to keep open.

**Closed** 2022-07-01 14:52 UTC
Labels: T-Defect, A-Soft-Logout, S-Critical, O-Uncommon
