### ISSUE TITLE
Audio messages & Inline player for audio

### ISSUE THREAD

**Issue by hoergen** [vector-im/element-android#1935] opened 2020-08-16 14:17 UTC
With the old riot-android there were several feature requests for playing sent audio directly in the android app. Sadly there were no progress on this topic, so I open this request once again so that hopefully someone can take away the pain of all enthusiasts to discuss this topic with the rest of the android world, why Element is not able to play natively audio files.

Instead of just press a play button, you have to download the file, hope it is in the notification area (often it is not) and if it is not, you have to search in your download folder then press on it, select your audio player.

The current _solution_ is to send far bigger video files, because they can be played by the app. As a tekki I can work with that, but again. as an enthusiast I have to discuss this over and over again with all the people I want to convince to switch over to matrix, the future of communication.

You would do us enthusiasts a huge favor to implement support for inline audio. Thank you 🌻

**Reference to the old issues**

- Audio messages https://github.com/vector-im/riot-android/issues/1237

- Inline player for audio uploads https://github.com/vector-im/riot-android/issues/57

**Comment by ralaud** [comment] 2020-08-16 15:00
Duplicate of #29

**Comment by inviridi** [comment] 2020-08-16 20:06
Would be a very useful feature for me and  the few people I convinced to join the party. Thanks for opening the ticket!

**Comment by kojid0** [comment] 2020-08-16 21:41
This is a must have feature but I guess it's harder to implement because all OS versions have to enable it at the same time (Android, iOS, web, desktop,...)

**Comment by hoergen** [comment] 2020-08-16 21:49
> This is a must have feature but I guess it's harder to implement because all OS versions have to enable it at the same time (Android, iOS, web, desktop,...)

On (Riot)Element Web is it working since ever. On iOS I don't know, but this is the Android repository, that's why I ask for support for Android ;)

**Comment by bmarty** [comment] 2020-08-17 12:01
Please upvote #29

**Closed by bmarty** 2020-08-17 12:01 UTC
Labels: type:suggestion
