### ISSUE TITLE
element io client crashes on android when handling large images

### ISSUE THREAD

**Issue by Xargas** [vector-im/element-android#2642] opened 2021-01-08 17:24 UTC
**Describe the bug**
When a large image is sent, the android client of element.io crashes when the image shall be opened.

**To Reproduce**
1. Get a large image (I used a jpg with 10064 x 2830 pixels from my desktop background)
2. send it in a private chat ("personal room with only two people inside")
3. open element.io on Android client
4. app crashes (Version: 1.0.13)

**Expected behavior**
If the image is to large to convert: an error message.
Or a short delay until the image is displayed.

**Screenshots**
n.a. -> crash

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco F2 Pro
 - OS: Android 10

Additional Info:
Some large pictures (example in use was 3456x4608 from DSLR) are also not shown in the android client.
The size 3456x4608 does not crash the client.
From my point of view this would indicate some general problem with the image processing code?

**Comment by skourismanolis** [comment] 2021-09-06 15:36
I've just experienced the same issue, here's the image I sent that crashed the app. Note that the file size is relatively small, at just 1.3MB.

![Famine-victims-since-1860s_March18](https://user-images.githubusercontent.com/44413349/132239834-179c87b9-d70d-49c1-90aa-2460b2eb02d4.png)

**Comment by ouchadam** [comment] 2022-02-25 12:18
relates to https://github.com/vector-im/element-android/pull/1952

**Comment by daniellekirkwood** [comment] 2022-05-31 15:31
Needs investigating as to whether this is still an issue.

**Comment by ericdecanini** [comment] 2022-06-08 12:31
It's unclear to me whether the issue is saying the crash happens when the timeline with the picture is opened or when the picture is expanded on after clicking it in the timeline.

Regardless, I managed to reproduce this in the second case. The issue is caused because the app struggles to handle large images. I'll investigate a possible fix for this

**Closed** 2022-06-16 09:04 UTC
Labels: T-Defect, Z-Crash, A-Media, S-Minor, O-Occasional, Z-WTF
