### ISSUE TITLE
Android-Web markdown inconsistency

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-android#6287] opened 2022-06-12 07:51 UTC
### Steps to reproduce

Markdown enabled in both Web and Android clients.
Lets send "21. st" from them...

|   |Element Web|Element Android|
|---|---|---|
|sent|21. st|21. st|
|shown|21. st|1. st|
|source|<pre>{<br>  "type": "m.room.message",<br>  "content": {<br>    "org.matrix.msc1767.message": [<br>      {<br>        "body": "21. st",<br>        "mimetype": "text/plain"<br>      },<br>      {<br>        "body": "<ol start=\"21\">\n&lt;li>st</li>\n</ol>\n",<br>        "mimetype": "text/html"<br>      }<br>    ],<br>    "body": "21. st",<br>    "msgtype": "m.text",<br>    "format": "org.matrix.custom.html",<br>    "formatted_body": "<ol start=\"21\">\n&lt;li>st</li>\n</ol>\n"<br>  }<br>}</pre>|<pre>{<br>  "content": {<br>    "body": "21. st",<br>    "format": "org.matrix.custom.html",<br>    "formatted_body": "<ol start=\"21\">\n&lt;li>st</li>\n</ol>",<br>    "msgtype": "m.text"<br>  },<br>  "room_id": "!XHJBYOUHLuCnrjsaUv:bolesiny.net",<br>  "type": "m.room.message"<br>}</pre>|

#### What did you expect?
Same text displayed.

#### What happened instead?
Different text displayed.

### Your phone model

Samsung Galaxy S20 FE

### Operating system version

Android 12

### Application version and app store

Element: 1.4.19

### Homeserver

own

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment] 2022-06-13 10:45
thanks for raising (and providing the clear examples)! going to close as a duplicate of https://github.com/vector-im/element-android/issues/4777

**Closed by ouchadam** 2022-06-13 10:45 UTC
Labels: T-Defect
