### ISSUE TITLE
Notification keeps resending

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/element-android#1673] opened 2020-07-12 17:01 UTC
If a notification isnt honored, riot.imx keeps resending it. So i get again a notificationssound and it resends it to my smartwatch (4 times)

0.91.4

**Comment by Rares95** [comment] 2020-07-22 18:40
I have this, but on the phone. Very weird (Android, latest Element version)

**Comment by orbitarte** [comment] 2020-07-29 07:24
Same here last version of element

**Comment by Wandelstock** [comment] 2020-09-11 23:24
Still the annoying bug. My smartwatch and tasker is going Bezirk

**Comment by Ji-eF** [comment] 2020-10-14 20:28
I also have this bug on my device : Nexus 6P with Lineageos 15 (Androis 8) and Element from F-Droid

**Comment by Ji-eF** [comment] 2020-10-16 09:59
It's quite hard to explain, so I hope I'll be clear enough :)
Upon a bit of investigation, it seems that the culprit is Element's "Silent notifications" category : 

- When getting a notification from a room with noisy notification, Element triggers "Noisy notification" category for Element's (in Android Settings > Apps Notifications) which seems OK.
- But then, the notification keeps popping up every few 10-seconds with the "Silent notification" category (when "Silent" is configured to "Vibrate" and/or "Sound" and/or "Blink LED".

The same behaviour appears while being on a video/phone call and you play around with notification area to make the voice call screen appear and hide ; the silent notification make the phone vibrate and sound, when configured to do so.

**Comment by ukanuk** [comment] 2021-06-10 12:09
it makes me very frustrated when Element notifications wake me up in the middle of the night due to this issue.

Notifications will start retriggering every minute because a friend in another time zone sent a message, and if it happens to be the 1% of the time when my Amazfit Bip hasn't detected me going to sleep and automatically turning on Do Not Disturb, then the watch starts vibrating and lighting up every minute and wakes me up. Every other app sends notifications only once.

Even if it only happened once a year, it makes me very frustrated when Element notifications wake me up in the middle of the night.

**Comment by ukanuk** [comment] 2021-06-19 16:16
I have this issue with the Google Play version of Element, while the other users say they have it with the F-Droid version. It seems to affect both versions.

**Comment by Vulkanodox** [comment] 2021-07-26 10:25
How is this shit not fixed yet? Just started to use element but this is unusable. No wonder why everybody wants to use whatsapp.

**Comment by ouchadam** [comment] 2021-10-01 12:53
able to reproduce this using the latest from develop 2b38c607b23b9ad087ac849f9b29e1da31360023 with a Xiaomi Mi Band 5

- Have a unread notification on the phone
- Join matrix-hq (even with no notifications)
- Proceed to get spammed with notifications on the connected device but nothing on the phone

This happens because each time we receive new events such as a message being read in a room we're retriggering the notification logic, and that logic currently causes a summary notification to be notified if we have a legitimate active notification (such as from a DM)  

#3657 fixes the issue by only updating the summary notification if a user facing notification has been triggered rather than every time the Sync has new events but doesn't cover the case where mentions/phone facing notifications will still notify the connected band every time

**Comment by bmarty** [comment] 2021-10-01 16:21
Fixed in Element 1.3.2 (see details in #3657)

**Closed** 2021-10-01 16:20 UTC
