### ISSUE TITLE
Invites become stuck when room is banned/deleted by admins

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#4720] opened 2021-12-15 10:47 UTC
### Steps to reproduce

1. Be invited to a room
2. A homeserver admin bans or deletes the room
3. No longer able to accept or reject the invite

#### What did you expect?
To be able to remove the invite

#### What happened instead?
The invite is stuck forever

--- 

when attempting to accept/reject the invite we get [undocumented](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-leave) (nor [here](https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3roomsroomidleave)) 404 with this body:

```json
{
    "errcode": "M_UNKNOWN",
    "error": "Not a known room"
}
```

- [ ] The Matrix SDK should just forget this room in this case.
- [ ] We will also have to check if the invite comes back during the next initial sync.

related synapse issue https://github.com/matrix-org/synapse/issues/11442

### Application version and app store

1.3.9

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment] 2021-12-15 10:48
Added `needs-product` to confirm the expected behaviour, should we inform the user the room is no longer valid?

**Comment by daniellekirkwood** [comment] 2022-02-22 16:36
Needs design for this use case... Tagging

**Comment by daniellekirkwood** [comment] 2022-05-02 18:24
I believe that the user should be told that the room is no longer available, with a message along the lines of "this may be because you're no longer invited, or because the room has been removed".

I don't think that the invite should unexpectedly disappear from the invite list, that will be jarring for users. 

However, this needs design thought and consideration. Tagging.

**Comment by t3chguy** [comment] 2023-02-16 17:29
Duplicate of https://github.com/vector-im/element-meta/issues/1010

**Closed by t3chguy** 2023-02-16 17:29 UTC
Labels: T-Defect, X-Needs-Design, A-Invite, S-Minor, O-Uncommon, Z-WTF
