### ISSUE TITLE
Keyboard gap in read only rooms 

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-android#7704] opened 2022-12-05 06:36 UTC
### Steps to reproduce

1. Enable rich text editor in Labs.
2. Go to some readonly room, e.g. announcement room.
3. There is visible a big gap below on the place where the input box supposed to be.

![obrazek](https://user-images.githubusercontent.com/15554561/205565187-c4cff3ea-91c4-4e40-94bd-3df00066c8c4.png)

#### What did you expect?
No gap.

#### What happened instead?
Gap.

### Your phone model

Samsung Galaxy S20 FE

### Operating system version

Android 12

### Application version and app store

1.5.10 [40105102] (G-8c111fea)

### Homeserver

self hosted Synapse 1.72.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2022-12-05 10:18
Thanks for reporting. Duplicate of #7680, fixed in Element 1.5.12.

**Closed by bmarty** 2022-12-05 10:18 UTC
Labels: T-Defect
