### ISSUE TITLE
Edit in Desktop-Element removes Reply-View in Android-Element

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-android#2565] opened 2020-12-20 22:23 UTC
Hi,

when you edit the content of a message with was a reply on another message the other "replied to view" is removed in the Android view of the edited message. This destroys the "reply history". @t3chguy mentioned in https://github.com/vector-im/element-web/issues/16007#issuecomment-748678750 this could be an Android bug.

Example:

# Desktop view

![Screenshot_2020-12-20_21-49-15](https://user-images.githubusercontent.com/44623983/102724185-140e0b80-430e-11eb-9123-5c2cb6b75145.png)

# Broken Android view

![Screenshot_2020-12-20_21-50-03](https://user-images.githubusercontent.com/44623983/102724187-196b5600-430e-11eb-9353-ddf44c5ecf88.png)

# Expected Android view

![Screenshot_2020-12-20_21-54-20](https://user-images.githubusercontent.com/44623983/102724254-a1e9f680-430e-11eb-891a-e2710604b376.png)

* Element Desktop version: 1.7.15 (on GNU/Linux Debian)
* Element Android version: 1.0.11 (F-Droid)

**Comment by benparsons** [comment] 2021-01-14 10:53
This is quite an annoyance!

**Comment by HarHarLinks** [comment] 2021-01-20 23:31
duplicate of #2448

**Closed** 2022-05-17 18:09 UTC
Labels: T-Defect, Z-UI UX, A-Replies, A-Timeline
