### ISSUE TITLE
Share to multiple recipients

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-android#3086] opened 2021-03-29 23:39 UTC
#### Is your feature request related to a problem? Please describe.
When sharing something from another app, one can only select one destination at a time. I believe that this could be improved to allow for sharing to multiple rooms in one go.

#### Describe the solution you'd like.
This could work alike to the "Create New Direct Room" view, where you can select rooms (as opposed to just people like the create DM view) to send the share to. A message editing box would replace the Invite friends, Contacts book and QR Code buttons.

#### Describe alternatives you've considered.
Alternatively, the current view could be modified to long-press select multiple rooms and a message editing box could be included somewhere when multiple recipients are selected.

#### Additional context
None

**Comment by expipiplus1** [comment] 2021-05-01 06:32
Looks like a duplicate of (half of) this: https://github.com/vector-im/element-android/issues/773

**Comment by expipiplus1** [comment] 2021-05-01 12:56
Just discovered that you can long press a recipient to enable selecting multiple.

**Comment by MadLittleMods** [comment] 2022-09-03 04:05
> Just discovered that you can long press a recipient to enable selecting multiple.

@TR-SLimey Does this solve your use case?

**Comment by 0x1a8510f2** [comment] 2022-09-03 11:18
@MadLittleMods pretty much, though it feels a little ugly. One of the selected rooms is opened after sending which feels weird, and sending to multiple people doesn't let you edit the message before sending. Also, one can't see any clear indication of how many rooms are selected so an accidental misclick can cause the user to send a message to a room they didn't intend to send it to.

The feature is there but I think it can be significantly improved.

That said, this issue can probably closed because, as @expipiplus1 said, it is a duplicate.

(It's me by the way, I have a new GH account :P)

**Closed** 2022-09-03 17:55 UTC
Labels: A-Share, T-Enhancement
