### ISSUE TITLE
can not make video calls

### ISSUE THREAD

**Issue by jjgalvez** [vector-im/element-android#7619] opened 2022-11-20 21:27 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

in a private encrypted room between two people both using android element 1.5.7 when making a video call who ever initiates the call their video can not be seen. Call A->B A's video is black B's works, call B->A, B's video is black A's can be seen.

#### What happened instead?
symmetrical video, both parties to see video

### Your phone model

Google Pixel 5a

### Operating system version

Android 12

### Application version and app store

Element version 1.5.7, olm 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bigCrash** [comment] 2022-11-30 23:24
Can confirm. At least for Fdroid Version 1.5.7 and 1.5.8 on a Oneplus Nord calling a Pixel 6a with some gplay Element version and vice versa. 

There might be more problematic constellations, however, I am not video calling that often.

**Comment by Game24h** [comment] 2022-12-08 18:45
Similar problem for me. Tried clearing cache, data, reinstalling and even flashing a different OS. Not working on Stock OS, CalyxOS and GrapheneOS. 

Phone model
Google Pixel 6 Pro

Operating system version
Android 13

Application version and app store
Element version 1.5.11, Fdroid

Homeserver
matrix.org

**Comment by acme4j** [comment] 2022-12-13 17:52
Can confirm this issue too.

First device: Google Pixel 6 Pro with GrapheneOS, Element 1.5.11 from f-droid.

Second device: Google Pixel 6 with stock OS, Element 1.5.11 from gplay.

Homeserver for both accounts: matrix.org.

**Comment by Fenisu** [comment] 2022-12-26 10:13
I can confirm this too. Between a Pixel 4a with Android 13 and Pixel 4a with Android 12.

**Comment by kojid0** [comment] 2023-01-04 16:28
I confirm as well.
Pixel 5 and Pixel 7, both with F-Droid version 1.5.11

**Comment by chrissi55** [comment] 2023-01-31 15:53
I can confirm this for Schildichat either.

Schildichat 1.5.8sc62 has adopted this bug from element as well.

The person who calls another sees both - the called person only see himself but a black screen of his voip partner.

**Comment by Joshndroid** [comment] 2023-02-04 08:36
Can confirm i am seeing this as well. Has been going on for a fair while. Had been pulling hair out and trying to work on jitsi within the main matrix self hosted instance to no avail. Tried both element app and schildichat, both have the issue as described.

**Comment by kojid0** [comment] 2023-02-04 08:50
I'm pretty disappointed that the team ignores such major issues but tbh I think this won't be fixed anymore. 
We probably have to wait until elementX is out (with native Element Call support instead of Jitsi).

**Comment by wilkgr76** [comment] 2023-02-11 14:17
Recently I have also run into this issue. The calls work to my partner's S10+ (Android 12) without issue, but do **not** work to her S22 (Android 13). This is consistently reproducible. The app is fully up to date on all devices, just using the matrix.org homeserver. 

I'm on an Edge 20 Fusion on Android 12.

I'd love to see this fixed, as it does make the app unusable for video calls.

**Comment by jwsp1** [comment] 2023-02-12 11:06
@bmarty just a heads-up: if you plan to implement #8077 soon, you don't need to fix this bug anymore.

**Comment by jwsp1** [comment] 2023-02-12 11:06
@bmarty just a reminder: if you plan to implement #8077 soon, you don't need to fix this bug anymore.

**Comment by schiessle** [comment] 2023-02-12 14:32
Maybe I miss something. But if I remember correctly 1:1 calls don't need Jitsi for quite some time already. I run my own Matrix server (without any Jitsi server) and could always do 1:1 calls before this bug come up.

**Comment by chrissi55** [comment] 2023-02-13 05:54
> ....I run my own Matrix server (without any Jitsi server) and could always do 1:1 calls before this bug come up.

You are right. I also have my own homeserver running matrix-synapse with the ability to make 1:1 calls without any jitsi interference! I own a jitsi server as well, but not specially as group call ability in matrix but more stand alone conference server.

The problems with the videocalls are severe because in my friendship calls (audio + video) are used very often and convincing people using matrix instead of other alternatives (that are able to deliver this feature!) will become a mammoth task

**Comment by Juha-Park-TII-SSRC** [comment] 2023-02-15 09:06
I think this problem caused by webrtc and jitsi upgrade(Upgrade Jitsi SDK to 6.2.2 and WebRtc to 1.106.1-jitsi-12039821. (https://github.com/vector-im/element-android/issues/6195).
This problem has happened to me since the v1.5.6.
I hope webrtc lib to be downgraded or upgraded to the latest version if possible.

**Comment by MatthieuDietrich** [comment] 2023-02-15 17:39
Yeah, I commented on https://github.com/vector-im/element-android/issues/7778 2 months back, and my kid is still sad that she couldn't see me during a weekly call from her tablet (she tried the Pi Epsilon client which seemed based on an old version of Element, but now it got updated and it fails too).

I'm sure the issue is on WebRTC calls, since I don't even have Jitsi configured.

**Comment by rajil** [comment] 2023-02-18 04:21
@bmarty @ara4n Lots of android devices have moved or moving to Android 13. Can this issue be prioritized on a urgent basis until Element Call debuts on Android.

**Comment by Juha-Park-TII-SSRC** [comment] 2023-02-21 07:36
I tried to avoid this issue by downgrading webRTC. I thought that android element uses webRTC and Jitsi-sdk separately, but actually the webRTC lib in the Jitsi-sdk is used for webRTC 1:1 call. so, I downgraded webRTC version in the Jitsi-sdk build. Now, I can make 1:1 webRTC call and Jitsi group call at the same time.

**Comment by Juha-Park-TII-SSRC** [comment] 2023-02-23 07:27
I am sharing what I observed and what I did.
* Observed
1) 1:1 video call has not working  since the webrtc and the Jitsi-sdk upgrade from the Element Android v1.5.6
    (Upgrade Jitsi SDK to 6.2.2 and WebRtc to 1.106.1-jitsi-12039821.)
2) New version of Jitsi Sdk is required to support recent Element-desktop.
3) It looks like that webRTC lib in the Jitsi-sdk is used for 1:1 video call(webRTC. Not Jitsi)
    (I downgraded the version of webRTC in vector module but it had the same issue.
     Even I commented webRTC including in the gradle file, 1:1 video call worked fine.)

*What I did.
  1) I used https://github.com/vector-im/element-android/blob/main/tools/jitsi/build_jisti_libs.sh
      to build jitsi android sdk.
  2) before building, I changed the version of webRTC in package.jon  like below.
      sed -i 's/"react-native-webrtc": "1.106.1"/"react-native-webrtc": "1.94.2"/' package.json
  3) Fix symbol error by commenting as below
      sed -i 's/.setEnableVolumeLogger(false)/ /' 
                  ./android/sdk/src/main/java/org/jitsi/meet/sd/ReactInstanceManagerHolder.java
  4) After building Jitsi android sdk, I changed the maven url of Jitsi to local repository in order to build Element Android.

Now, I have the latest Jitsi-android-sdk(7.0.1) but old webRTC. And Jitsi group call and 1:1 webRTC video call works fine
in the Element Android v1.5.22. 

You can download the compressed tar file from https://github.com/tiiuae/element-android/commit/dc0bf7569c378e04db39f102fd6fee9f78fe0ff3 and use it.

**Comment by bmarty** [comment] 2023-02-28 15:05
Thanks for your investigation @Juha-Park-TII-SSRC . We will probably need to use the latest Jitsi version (7.0.1)

> before building, I changed the version of webRTC in package.jon like below.
sed -i 's/"react-native-webrtc": "1.106.1"/"react-native-webrtc": "1.94.2"/' package.json

I suppose 1-1 call was not working with Jitsi 7.0.1 and WebRTC `1.106.1`? 

(I am trying to repro the issue at the moment, but 1-1 video call is working properly between 2 API 32 Android Emulators...)

**Comment by Juha-Park-TII-SSRC** [comment] 2023-03-02 17:00
> Thanks for your investigation @Juha-Park-TII-SSRC . We will probably need to use the latest Jitsi version (7.0.1)
> 
> > before building, I changed the version of webRTC in package.jon like below.
> > sed -i 's/"react-native-webrtc": "1.106.1"/"react-native-webrtc": "1.94.2"/' package.json
> 
> I suppose 1-1 call was not working with Jitsi 7.0.1 and WebRTC `1.106.1`?
> 
> (I am trying to repro the issue at the moment, but 1-1 video call is working properly between 2 API 33 Android Emulators...)

When I tested 7.0.1, it also had the same issue. Anyway I changed the webRTC version in the 7.0.1 and it worked.

I believe that the emulator will use S/W codec and if the issue is related to H/W codec, it will not have the issue.

My question is, why it happens in one way if the issue is related to H/W codec. Caller and Sender will use the same version of webRTC and it will be H/W codec.

**Comment by bmarty** [comment] 2023-03-06 15:51
Waiting for a fix (https://github.com/react-native-webrtc/react-native-webrtc/issues/1332#issuecomment-1449443752) in dependencies. Once available we will upgrade our Jitsi and WebRTC version.

**Comment by rajil** [comment] 2023-04-06 02:43
The related react-native-webrtc is fixed to use software encoding (https://github.com/react-native-webrtc/react-native-webrtc/issues/1354) via M111 release. Can Element go ahead and use that for the next release please?

**Comment by saghul** [comment] 2023-04-13 16:14
There will be one in 1-2 weeks time.

**Comment by vincent-k** [comment] 2023-04-26 00:04
Great news, jitsi SDK 8.0.0 has just been released with WebRTC M111 bump.

**Comment by rajil** [comment] 2023-04-28 15:32
@bmarty It will be great if we can get this fixed for the next release.

**Comment by bmarty** [comment] 2023-05-02 11:26
Hello @saghul , I am trying to upgrade Jitsi SDK to version 8.1.1 but I got this error when compiling the project Element Android:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vector:dataBindingMergeDependencyArtifactsKotlinCryptoDebug'.
> Could not resolve all files for configuration ':vector:kotlinCryptoDebugCompileClasspath'.
   > Could not find org.jitsi:webrtc:111.0.1.
     Required by:
         project :vector > com.facebook.react:react-native-webrtc:111.0.0-jitsi-13672566
```

This is strange that `react-native-webrtc` has a dependency on `org.jitsi:webrtc`, also the version number `111.0.1` is a bit suspicious. 

I also tried 8.0.0 and 8.1.0 nad got the same error.

WDYT?

**Comment by saghul** [comment] 2023-05-02 11:57
What's suspicious about it? That is our WebRTC build, which RN-WebRTC uses.

Do you have the MavenCentral repo enabled?

**Comment by bmarty** [comment] 2023-05-02 12:11
OK, I did not realize it was an external dependency. I can now compile the project. the last `1` in `111.0.1` was suspicious to me, since the version of `react-native-webrtc` is `111.0.0`. Anyway this is fine now, thanks.

**Comment by saghul** [comment] 2023-05-03 05:54
I see the confusion.

Generally speaking only the major needs to match, we might do more WebRTC builds to cherry-pick fixes, but there is no need to make a new RN-WebRTC release.

**Closed** 2023-05-03 07:27 UTC
Labels: T-Defect, X-Blocked, S-Major, O-Frequent, A-VideoCall, Team: Element X Platform

**Comment by bmarty** [comment] 2023-05-17 13:29
Fix will be available in Element Android 1.6.0

**Comment by kojid0** [comment] 2023-05-30 17:56
When will 1.6.0 (or 1.6.1) be available on F-Droid?

**Comment by Stef-33560** [comment] 2023-06-02 18:00
Still no news about an update ? :'(

**Comment by supertalent007** [comment] 2024-09-15 23:48
I can not make a video call between android and ios app.
It shows only black screen on ios app.
